#!/bin/sh
set -e
dst_dir="/Users/kcrca/Library/Application Support/minecraft/saves/AllStuff/datapacks/allstuff/data/allstuff"
find functions -type f -delete
/Users/kcrca/allstuff/venv/bin/python /Users/kcrca/allstuff/allstuff/main.py
find "$dst_dir"/functions -type f -delete
test -d "$dst_dir"/tags && rm -rf "$dst_dir"/tags/*
echo + 'cp functions/* "$dst_dir"/functions/'
tar cf - functions tags | (cd "$dst_dir" ; tar xf -)
