from enum import Enum


class LowerEnum(Enum):
    def __str__(self):
        return self.name.lower()


class ValueEnum(Enum):
    def __str__(self):
        return super().value


class Advancement(ValueEnum):
    MINECRAFT = "story/root"
    STONE_AGE = "story/mine_stone"
    GETTING_AN_UPGRADE = "story/upgrade_tools"
    ACQUIRE_HARDWARE = "story/smelt_iron"
    SUIT_UP = "story/obtain_armor"
    HOT_STUFF = "story/lava_bucket"
    ISNT_IT_IRON_PICK = "story/iron_tools"
    NOT_TODAY_THANK_YOU = "story/deflect_arrow"
    ICE_BUCKET_CHALLENGE = "story/form_obsidian"
    DIAMONDS = "story/mine_diamond"
    WE_NEED_TO_GO_DEEPER = "story/enter_the_nether"
    COVER_ME_WITH_DIAMONDS = "story/shiny_gear"
    ENCHANTER = "story/enchant_item"
    ZOMBIE_DOCTOR = "story/cure_zombie_villager"
    EYE_SPY = "story/follow_ender_eye"
    ENTER_THE_END = "story/enter_the_end"
    NETHER = "nether/root"
    RETURN_TO_SENDER = "nether/return_to_sender"
    THOSE_WERE_THE_DAYS = "nether/find_bastion"
    HIDDEN_IN_THE_DEPTHS = "nether/obtain_ancient_debris"
    SUBSPACE_BUBBLE = "nether/fast_travel"
    A_TERRIBLE_FORTRESS = "nether/find_fortress"
    WHO_IS_CUTTING_ONIONS = "nether/obtain_crying_obsidian"
    OH_SHINY = "nether/distract_piglin"
    THIS_BOAT_HAS_LEGS = "nether/ride_strider"
    UNEASY_ALLIANCE = "nether/uneasy_alliance"
    WAR_PIGS = "nether/loot_bastion"
    COUNTRY_LODE_TAKE_ME_HOME = "nether/use_lodestone"
    COVER_ME_IN_DEBRIS = "nether/netherite_armor"
    SPOOKY_SCARY_SKELETON = "nether/get_wither_skull"
    INTO_FIRE = "nether/obtain_blaze_rod"
    NOT_QUITE_NINE_LIVES = "nether/charge_respawn_anchor"
    FEELS_LIKE_HOME = "nether/ride_strider_in_overworld_lava"
    HOT_TOURIST_DESTINATIONS = "nether/explore_nether"
    WITHERING_HEIGHTS = "nether/summon_wither"
    LOCAL_BREWERY = "nether/brew_potion"
    BRING_HOME_THE_BEACON = "nether/create_beacon"
    A_FURIOUS_COCKTAIL = "nether/all_potions"
    BEACONATOR = "nether/create_full_beacon"
    HOW_DID_WE_GET_HERE = "nether/all_effects"
    THE_END = "end/root"
    FREE_THE_END = "end/kill_dragon"
    THE_NEXT_GENERATION = "end/dragon_egg"
    REMOTE_GETAWAY = "end/enter_end_gateway"
    THE_END_AGAIN = "end/respawn_dragon"
    YOU_NEED_A_MINT = "end/dragon_breath"
    THE_CITY_AT_THE_END_OF_THE_GAME = "end/find_end_city"
    SKYS_THE_LIMIT = "end/elytra"
    GREAT_VIEW_FROM_UP_HERE = "end/levitate"
    ADVENTURE = "adventure/root"
    VOLUNTARY_EXILE = "adventure/voluntary_exile"
    IS_IT_A_BIRD = "adventure/spyglass_at_parrot"
    MONSTER_HUNTER = "adventure/kill_a_mob"
    WHAT_A_DEAL = "adventure/trade"
    STICKY_SITUATION = "adventure/honey_block_slide"
    OL_BETSY = "adventure/ol_betsy"
    SURGE_PROTECTOR = "adventure/lightning_rod_with_villager_no_fire"
    CAVES__CLIFFS = "adventure/fall_from_world_height"
    SNEAK_100 = "adventure/avoid_vibration"
    SWEET_DREAMS = "adventure/sleep_in_bed"
    HERO_OF_THE_VILLAGE = "adventure/hero_of_the_village"
    IS_IT_A_BALLOON = "adventure/spyglass_at_ghast"
    A_THROWAWAY_JOKE = "adventure/throw_trident"
    IT_SPREADS = "adventure/kill_mob_near_sculk_catalyst"
    TAKE_AIM = "adventure/shoot_arrow"
    MONSTERS_HUNTED = "adventure/kill_all_mobs"
    POSTMORTAL = "adventure/totem_of_undying"
    HIRED_HELP = "adventure/summon_iron_golem"
    STAR_TRADER = "adventure/trade_at_world_height"
    TWO_BIRDS_ONE_ARROW = "adventure/two_birds_one_arrow"
    WHOS_THE_PILLAGER_NOW = "adventure/whos_the_pillager_now"
    ARBALISTIC = "adventure/arbalistic"
    ADVENTURING_TIME = "adventure/adventuring_time"
    SOUND_OF_MUSIC = "adventure/play_jukebox_in_meadows"
    LIGHT_AS_A_RABBIT = "adventure/walk_on_powder_snow_with_leather_boots"
    IS_IT_A_PLANE = "adventure/spyglass_at_dragon"
    VERY_VERY_FRIGHTENING = "adventure/very_very_frightening"
    SNIPER_DUEL = "adventure/sniper_duel"
    BULLSEYE = "adventure/bullseye"
    HUSBANDRY = "husbandry/root"
    BEE_OUR_GUEST = "husbandry/safely_harvest_honey"
    THE_PARROTS_AND_THE_BATS = "husbandry/breed_an_animal"
    YOUVE_GOT_A_FRIEND_IN_ME = "husbandry/allay_deliver_item_to_player"
    WHATEVER_FLOATS_YOUR_GOAT = "husbandry/ride_a_boat_with_a_goat"
    BEST_FRIENDS_FOREVER = "husbandry/tame_an_animal"
    GLOW_AND_BEHOLD = "husbandry/make_a_sign_glow"
    FISHY_BUSINESS = "husbandry/fishy_business"
    TOTAL_BEELOCATION = "husbandry/silk_touch_nest"
    BUKKIT_BUKKIT = "husbandry/tadpole_in_a_bucket"
    A_SEEDY_PLACE = "husbandry/plant_seed"
    WAX_ON = "husbandry/wax_on"
    TWO_BY_TWO = "husbandry/bred_all_animals"
    BIRTHDAY_SONG = "husbandry/allay_deliver_cake_to_note_block"
    A_COMPLETE_CATALOGUE = "husbandry/complete_catalogue"
    TACTICAL_FISHING = "husbandry/tactical_fishing"
    WHEN_THE_SQUAD_HOPS_INTO_TOWN = "husbandry/leash_all_frog_variants"
    A_BALANCED_DIET = "husbandry/balanced_diet"
    SERIOUS_DEDICATION = "husbandry/obtain_netherite_hoe"
    WAX_OFF = "husbandry/wax_off"
    THE_CUTEST_PREDATOR = "husbandry/axolotl_in_a_bucket"
    WITH_OUR_POWERS_COMBINED = "husbandry/froglights"
    THE_HEALING_POWER_OF_FRIENDSHIP = "husbandry/kill_axolotl_target"
