from enum import Enum
class ValueEnum(Enum):
    def __str__(self):
        return super().value


# noinspection SpellCheckingInspection
class Advancement(ValueEnum):
    MINECRAFT = "story/root"
    """The heart and story of the game."""
    STONE_AGE = "story/mine_stone"
    """Mine stone with your new pickaxe."""
    GETTING_AN_UPGRADE = "story/upgrade_tools"
    """Construct a better pickaxe."""
    ACQUIRE_HARDWARE = "story/smelt_iron"
    """Smelt an iron ingot."""
    SUIT_UP = "story/obtain_armor"
    """Protect yourself with a piece of iron armor."""
    HOT_STUFF = "story/lava_bucket"
    """Fill a bucket with lava."""
    ISNT_IT_IRON_PICK = "story/iron_tools"
    """Upgrade your pickaxe."""
    NOT_TODAY_THANK_YOU = "story/deflect_arrow"
    """Block a projectile using your shield."""
    ICE_BUCKET_CHALLENGE = "story/form_obsidian"
    """Obtain a block of obsidian."""
    DIAMONDS = "story/mine_diamond"
    """Acquire diamonds."""
    WE_NEED_TO_GO_DEEPER = "story/enter_the_nether"
    """Build, light and enter a Nether Portal."""
    COVER_ME_WITH_DIAMONDS = "story/shiny_gear"
    """Diamond armor saves lives."""
    ENCHANTER = "story/enchant_item"
    """Enchant an item at an Enchantment Table."""
    ZOMBIE_DOCTOR = "story/cure_zombie_villager"
    """Weaken and then cure a Zombie Villager."""
    EYE_SPY = "story/follow_ender_eye"
    """Follow an Ender Eye."""
    ENTER_THE_END = "story/enter_the_end"
    """Enter the End Portal."""
    NETHER = "nether/root"
    """Bring summer clothes."""
    RETURN_TO_SENDER = "nether/return_to_sender"
    """Destroy a Ghast with a fireball."""
    THOSE_WERE_THE_DAYS = "nether/find_bastion"
    """Enter a Bastion Remnant."""
    HIDDEN_IN_THE_DEPTHS = "nether/obtain_ancient_debris"
    """Obtain Ancient Debris."""
    SUBSPACE_BUBBLE = "nether/fast_travel"
    """Use the Nether to travel 7 km in the Overworld."""
    A_TERRIBLE_FORTRESS = "nether/find_fortress"
    """Break your way into a Nether Fortress."""
    WHO_IS_CUTTING_ONIONS = "nether/obtain_crying_obsidian"
    """Obtain Crying Obsidian."""
    OH_SHINY = "nether/distract_piglin"
    """Distract Piglins with gold."""
    THIS_BOAT_HAS_LEGS = "nether/ride_strider"
    """Ride a Strider with a Warped Fungus on a Stick."""
    UNEASY_ALLIANCE = "nether/uneasy_alliance"
    """Rescue a Ghast from the Nether, bring it safely home to the Overworld... and then kill it."""
    WAR_PIGS = "nether/loot_bastion"
    """Loot a chest in a Bastion Remnant."""
    COUNTRY_LODE_TAKE_ME_HOME = "nether/use_lodestone"
    """Use a compass on a Lodestone."""
    COVER_ME_IN_DEBRIS = "nether/netherite_armor"
    """Get a full suit of Netherite armor."""
    SPOOKY_SCARY_SKELETON = "nether/get_wither_skull"
    """Obtain a Wither Skeleton's skull."""
    INTO_FIRE = "nether/obtain_blaze_rod"
    """Relieve a Blaze of its rod."""
    NOT_QUITE_NINE_LIVES = "nether/charge_respawn_anchor"
    """Charge a Respawn Anchor to the maximum."""
    FEELS_LIKE_HOME = "nether/ride_strider_in_overworld_lava"
    """Take a Strider for a loooong ride on a lava lake in the Overworld."""
    HOT_TOURIST_DESTINATIONS = "nether/explore_nether"
    """Explore all Nether biomes."""
    WITHERING_HEIGHTS = "nether/summon_wither"
    """Summon the Wither."""
    LOCAL_BREWERY = "nether/brew_potion"
    """Brew a potion."""
    BRING_HOME_THE_BEACON = "nether/create_beacon"
    """Construct and place a beacon."""
    A_FURIOUS_COCKTAIL = "nether/all_potions"
    """Have every potion effect applied at the same time."""
    BEACONATOR = "nether/create_full_beacon"
    """Bring a beacon to full power."""
    HOW_DID_WE_GET_HERE = "nether/all_effects"
    """Have every effect applied at the same time."""
    THE_END = "end/root"
    """Or the beginning?"""
    FREE_THE_END = "end/kill_dragon"
    """Good luck."""
    THE_NEXT_GENERATION = "end/dragon_egg"
    """Hold the Dragon Egg."""
    REMOTE_GETAWAY = "end/enter_end_gateway"
    """Escape the island."""
    THE_END_AGAIN = "end/respawn_dragon"
    """Respawn the Ender Dragon."""
    YOU_NEED_A_MINT = "end/dragon_breath"
    """Collect dragon's breath in a glass bottle."""
    THE_CITY_AT_THE_END_OF_THE_GAME = "end/find_end_city"
    """Go on in, what could happen?"""
    SKYS_THE_LIMIT = "end/elytra"
    """Find elytra."""
    GREAT_VIEW_FROM_UP_HERE = "end/levitate"
    """Levitate up 50 blocks from the attacks of a Shulker."""
    ADVENTURE = "adventure/root"
    """Adventure, exploration, and combat."""
    VOLUNTARY_EXILE = "adventure/voluntary_exile"
    """Kill a raid captain.Maybe consider staying away from villages for the time being..."""
    IS_IT_A_BIRD = "adventure/spyglass_at_parrot"
    """Look at a parrot through a spyglass."""
    MONSTER_HUNTER = "adventure/kill_a_mob"
    """Kill any hostile monster."""
    WHAT_A_DEAL = "adventure/trade"
    """Successfully trade with a Villager."""
    STICKY_SITUATION = "adventure/honey_block_slide"
    """Jump into a Honey Block to break your fall."""
    OL_BETSY = "adventure/ol_betsy"
    """Shoot a crossbow."""
    SURGE_PROTECTOR = "adventure/lightning_rod_with_villager_no_fire"
    """Protect a villager from an undesired shock without starting a fire."""
    CAVES__CLIFFS = "adventure/fall_from_world_height"
    """Free fall from the top of the world (build limit) to the bottom of the world and survive."""
    SNEAK_100 = "adventure/avoid_vibration"
    """Sneak near a Sculk Sensor or Warden to prevent it from detecting you."""
    SWEET_DREAMS = "adventure/sleep_in_bed"
    """Sleep in a bed to change your respawn point."""
    HERO_OF_THE_VILLAGE = "adventure/hero_of_the_village"
    """Successfully defend a village from a raid."""
    IS_IT_A_BALLOON = "adventure/spyglass_at_ghast"
    """Look at a ghast through a spyglass."""
    A_THROWAWAY_JOKE = "adventure/throw_trident"
    """Throw a trident at something.Note: Throwing away your only weapon is not a good idea."""
    IT_SPREADS = "adventure/kill_mob_near_sculk_catalyst"
    """Kill a mob near a Sculk Catalyst."""
    TAKE_AIM = "adventure/shoot_arrow"
    """Shoot something with an arrow."""
    MONSTERS_HUNTED = "adventure/kill_all_mobs"
    """Kill one of every hostile monster."""
    POSTMORTAL = "adventure/totem_of_undying"
    """Use a Totem of Undying to cheat death."""
    HIRED_HELP = "adventure/summon_iron_golem"
    """Summon an Iron Golem to help defend a village."""
    STAR_TRADER = "adventure/trade_at_world_height"
    """Trade with a Villager at the build height limit."""
    TWO_BIRDS_ONE_ARROW = "adventure/two_birds_one_arrow"
    """Kill two Phantoms with a piercing arrow."""
    WHOS_THE_PILLAGER_NOW = "adventure/whos_the_pillager_now"
    """Give a Pillager a taste of their own medicine."""
    ARBALISTIC = "adventure/arbalistic"
    """Kill five unique mobs with one crossbow shot."""
    ADVENTURING_TIME = "adventure/adventuring_time"
    """Discover every biome."""
    SOUND_OF_MUSIC = "adventure/play_jukebox_in_meadows"
    """Make the Meadows come alive with the sound of music from a Jukebox."""
    LIGHT_AS_A_RABBIT = "adventure/walk_on_powder_snow_with_leather_boots"
    """Walk on powder snow...without sinking in it."""
    IS_IT_A_PLANE = "adventure/spyglass_at_dragon"
    """Look at the Ender Dragon through a spyglass."""
    VERY_VERY_FRIGHTENING = "adventure/very_very_frightening"
    """Strike a Villager with lightning."""
    SNIPER_DUEL = "adventure/sniper_duel"
    """Kill a Skeleton from at least 50 meters away."""
    BULLSEYE = "adventure/bullseye"
    """Hit the bullseye of a Target block from at least 30 meters away."""
    HUSBANDRY = "husbandry/root"
    """The world is full of friends and food."""
    BEE_OUR_GUEST = "husbandry/safely_harvest_honey"
    """Use a Campfire to collect Honey from a Beehive using a Bottle without aggravating the bees."""
    THE_PARROTS_AND_THE_BATS = "husbandry/breed_an_animal"
    """Breed two animals together."""
    YOUVE_GOT_A_FRIEND_IN_ME = "husbandry/allay_deliver_item_to_player"
    """Have an Allay deliver items to you."""
    WHATEVER_FLOATS_YOUR_GOAT = "husbandry/ride_a_boat_with_a_goat"
    """Get in a Boat and float with a Goat."""
    BEST_FRIENDS_FOREVER = "husbandry/tame_an_animal"
    """Tame an animal."""
    GLOW_AND_BEHOLD = "husbandry/make_a_sign_glow"
    """Make the text of a sign glow."""
    FISHY_BUSINESS = "husbandry/fishy_business"
    """Catch a fish."""
    TOTAL_BEELOCATION = "husbandry/silk_touch_nest"
    """Move a Bee Nest, with 3 bees inside, using Silk Touch."""
    BUKKIT_BUKKIT = "husbandry/tadpole_in_a_bucket"
    """Catch a Tadpole in a Bucket."""
    A_SEEDY_PLACE = "husbandry/plant_seed"
    """Plant a seed and watch it grow."""
    WAX_ON = "husbandry/wax_on"
    """Apply Honeycomb to a Copper block!"""
    TWO_BY_TWO = "husbandry/bred_all_animals"
    """Breed all the animals!"""
    BIRTHDAY_SONG = "husbandry/allay_deliver_cake_to_note_block"
    """Have an Allay drop a Cake at a Note Block."""
    A_COMPLETE_CATALOGUE = "husbandry/complete_catalogue"
    """Tame all cat variants!"""
    TACTICAL_FISHING = "husbandry/tactical_fishing"
    """Catch a fish... without a fishing rod!"""
    WHEN_THE_SQUAD_HOPS_INTO_TOWN = "husbandry/leash_all_frog_variants"
    """Get each Frog variant on a Lead."""
    A_BALANCED_DIET = "husbandry/balanced_diet"
    """Eat everything that is edible, even if it's not good for you."""
    SERIOUS_DEDICATION = "husbandry/obtain_netherite_hoe"
    """Use a Netherite Ingot to upgrade a hoe, and then reevaluate your life choices."""
    WAX_OFF = "husbandry/wax_off"
    """Scrape Wax off of a Copper block!"""
    THE_CUTEST_PREDATOR = "husbandry/axolotl_in_a_bucket"
    """Catch an axolotl in a bucket."""
    WITH_OUR_POWERS_COMBINED = "husbandry/froglights"
    """Have all Froglights in your inventory."""
    THE_HEALING_POWER_OF_FRIENDSHIP = "husbandry/kill_axolotl_target"
    """Team up with an axolotl and win a fight."""


# noinspection SpellCheckingInspection
class Effects(ValueEnum):
    SPEED = "speed"
    """Increases walking speed; higher levels make the affected entity faster and increases the player's field of view when affected."""
    SLOWNESS = "slowness"
    """Decreases walking speed; higher levels make the affected entity slower and decreases the player's field of view when affected."""
    HASTE = "haste"
    """Increases mining and attack speed, higher levels increase the player's mining and attack speed."""
    MINING_FATIGUE = "mining_fatigue"
    """Decreases mining and attack speed, higher levels decrease the player's mining and attack speed."""
    STRENGTH = "strength"
    """Increases melee damage, higher levels make the affected entity do more melee damage."""
    INSTANT_HEALTH = "instant_health"
    """Heals living entities, damages undead, higher levels heal more health and do more damage."""
    INSTANT_DAMAGE = "instant_damage"
    """Damages living entities, heals undead, higher levels do more damage and heal more health."""
    JUMP_BOOST = "jump_boost"
    """Increases jump height and reduces fall damage, higher levels make the affected entity jump higher and reduces more fall damage."""
    NAUSEA = "nausea"
    """Wobbles and warps the screen."""
    REGENERATION = "regeneration"
    """Regenerates health over time, higher levels make health regenerate quicker."""
    RESISTANCE = "resistance"
    """Reduces damage, higher levels reduce more damage."""
    FIRE_RESISTANCE = "fire_resistance"
    """Prevents the affected entity from taking damage due to Fire, lava and other sources of fire damage."""
    WATER_BREATHING = "water_breathing"
    """Prevents drowning and lets the affected entity breathe underwater."""
    INVISIBILITY = "invisibility"
    """Grants invisibility, making the affected entity invisible (but not the item they hold or the armor they wear), and reduces other mobs' detection range for the affected entity, higher levels reduce other mobs' detection range more."""
    BLINDNESS = "blindness"
    """Impairs vision and disables the ability to sprint and critical hit."""
    NIGHT_VISION = "night_vision"
    """Lets the player see well in darkness and underwater."""
    HUNGER = "hunger"
    """Increases food exhaustion, higher levels cause the player to starve quicker."""
    WEAKNESS = "weakness"
    """Decreases melee damage, higher levels decrease more melee damage."""
    POISON = "poison"
    """Inflicts damage over time (but can't kill), higher levels do more damage per second, doesn't affect undead."""
    WITHER = "wither"
    """Inflicts damage over time (can kill), higher levels do more damage per second."""
    HEALTH_BOOST = "health_boost"
    """Increases maximum health, higher levels give the affected entity more maximum health."""
    ABSORPTION = "absorption"
    """Adds damage absorption (additional hearts that can't be regenerated), higher levels give more absorption."""
    SATURATION = "saturation"
    """Restores hunger and saturation."""
    GLOWING = "glowing"
    """Outlines the affected entity (can be seen through blocks)."""
    LEVITATION = "levitation"
    """Floats the affected entity upward."""
    LUCK_ = "luck"
    """Can increase chances of high-quality and more loot, higher levels increase the chances of better loot."""
    BAD_LUCK_ = "unluck"
    """Can reduce chances of high-quality and more loot, higher levels reduce the chance of good loot."""
    FATAL_POISON = "fatal_poison"
    """Inflicts damage over time and potentially kills."""
    SLOW_FALLING = "slow_falling"
    """Decreases falling speed and negates fall damage."""
    CONDUIT_POWER = "conduit_power"
    """Increases underwater visibility and mining speed, prevents drowning."""
    DOLPHINS_GRACE = "dolphins_grace"
    """Increases swimming speed (only obtainable from dolphins)."""
    BAD_OMEN = "bad_omen"
    """Causes an illager raid to start upon entering a village (only received from an Illager captain upon its death), higher levels cause a more difficult raid."""
    HERO_OF_THE_VILLAGE = "hero_of_the_village"
    """Gives discounts on trades with villagers, and makes villagers throw items at the player depending on their profession."""
    DARKNESS = "darkness"
    """Darkens the players screen."""


# noinspection SpellCheckingInspection
class Enchantments(ValueEnum):
    AQUA_AFFINITY = "aqua_affinity"
    """Increases underwater mining speed."""
    BANE_OF_ARTHROPODS = "bane_of_arthropods"
    """Increases damage and applies Slowness IV to arthropod mobs (spiders, cave spiders, silverfish, endermites and bees)."""
    BLAST_PROTECTION = "blast_protection"
    """Reduces explosion damage and knockback."""
    CHANNELING = "channeling"
    """During thunderstorms, tridents will be able to strike hit enemies with a lightning bolt."""
    CLEAVING_ = "cleaving_"
    """Increases damage and shield stunning."""
    CURSE_OF_BINDING = "curse_of_binding"
    """Items cannot be removed from armor slots."""
    CURSE_OF_VANISHING = "curse_of_vanishing"
    """Item disappears on death."""
    DEPTH_STRIDER = "depth_strider"
    """Increases underwater movement speed."""
    EFFICIENCY = "efficiency"
    """Increases tool speed, as well as the chance for axes to disable shields."""
    FEATHER_FALLING = "feather_falling"
    """Reduces fall damage."""
    FIRE_ASPECT = "fire_aspect"
    """Sets target on fire."""
    FIRE_PROTECTION = "fire_protection"
    """Reduces fire damage and burn time.Mutually exclusive with other protections."""
    FLAME = "flame"
    """Arrows shot are ignited and deal fire damage to the target."""
    FORTUNE = "fortune"
    """Increases the amount of block drops."""
    FROST_WALKER = "frost_walker"
    """Allows the player to walk on water by freezing the water under their feet."""
    IMPALING = "impaling"
    """Increases damage against aquatic mobs. In Bedrock Edition, increases damage against mobs in water or rain."""
    INFINITY = "infinity"
    """Prevents consumption of arrows."""
    KNOCKBACK = "knockback"
    """Increases knockback."""
    LOOTING = "looting"
    """Increases mob loot."""
    LOYALTY = "loyalty"
    """Trident returns after_cmds being thrown."""
    LUCK_OF_THE_SEA = "luck_of_the_sea"
    """Increases rate of good loot (enchanting books, etc.)."""
    LURE = "lure"
    """Decreases time for bites."""
    MENDING = "mending"
    """Repairs the item using experience."""
    MULTISHOT = "multishot"
    """Fires 3 arrows at the same time."""
    PIERCING = "piercing"
    """Arrows pierce entities, allowing for arrows to pierce through stacks of mobs. Available only to the crossbow."""
    POWER = "power"
    """Increases arrow damage."""
    PROJECTILE_PROTECTION = "projectile_protection"
    """Reduces damage from projectiles."""
    PROTECTION = "protection"
    """Reduces generic damage."""
    PUNCH = "punch"
    """Increases arrow knockback."""
    QUICK_CHARGE = "quick_charge"
    """Decreases crossbow charging time."""
    RESPIRATION = "respiration"
    """Extends underwater breathing time."""
    RIPTIDE = "riptide"
    """Trident launches player with itself when thrown while in water or rain."""
    SHARPNESS = "sharpness"
    """Increases melee damage."""
    SILK_TOUCH = "silk_touch"
    """Mined blocks drop themselves."""
    SMITE = "smite"
    """Increases damage to the undead."""
    SOUL_SPEED = "soul_speed"
    """Increases movement speed on soul soil."""
    SWEEPING_EDGE = "sweeping_edge"
    """Increases sweeping attack damage."""
    SWIFT_SNEAK = "swift_sneak"
    """Increases sneaking speed."""
    THORNS = "thorns"
    """Taking damage causes the attacker to also take damage."""
    UNBREAKING = "unbreaking"
    """Reduces durability damage."""

    def max_level(ench):
      return {'aqua_affinity': 1, 'bane_of_arthropods': 5, 'blast_protection': 4, 'channeling': 1, 'cleaving_': 3, 'curse_of_binding': 1, 'curse_of_vanishing': 1, 'depth_strider': 3, 'efficiency': 5, 'feather_falling': 4, 'fire_aspect': 2, 'fire_protection': 4, 'flame': 1, 'fortune': 3, 'frost_walker': 2, 'impaling': 5, 'infinity': 1, 'knockback': 2, 'looting': 3, 'loyalty': 3, 'luck_of_the_sea': 3, 'lure': 3, 'mending': 1, 'multishot': 1, 'piercing': 4, 'power': 5, 'projectile_protection': 4, 'protection': 4, 'punch': 2, 'quick_charge': 3, 'respiration': 3, 'riptide': 3, 'sharpness': 5, 'silk_touch': 1, 'smite': 5, 'soul_speed': 3, 'sweeping_edge': 3, 'swift_sneak': 3, 'thorns': 3, 'unbreaking': 3}[ench.value]


# noinspection SpellCheckingInspection
class GameRules(ValueEnum):
    ANNOUNCE_ADVANCEMENTS = "announceAdvancements"
    """Whether advancements should be announced in chat."""
    COMMAND_BLOCK_OUTPUT = "commandBlockOutput"
    """Whether command blocks should notify admins when they perform commands."""
    DISABLE_ELYTRA_MOVEMENT_CHECK = "disableElytraMovementCheck"
    """Whether the server should skip checking player speed when the player is wearing elytra. Often helps with jittering due to lag in multiplayer."""
    DISABLE_RAIDS = "disableRaids"
    """Whether raids are disabled."""
    DO_DAYLIGHT_CYCLE = "doDaylightCycle"
    """Whether the daylight cycle and moon phases progress."""
    DO_ENTITY_DROPS = "doEntityDrops"
    """Whether entities that are not mobs should have drops."""
    DO_FIRE_TICK = "doFireTick"
    """Whether fire should spread and naturally extinguish."""
    DO_INSOMNIA = "doInsomnia"
    """Whether phantoms can spawn in the nighttime."""
    DO_IMMEDIATE_RESPAWN = "doImmediateRespawn"
    """Players respawn immediately without showing the death screen."""
    DO_LIMITED_CRAFTING = "doLimitedCrafting"
    """Whether players should be able to craft only those recipes that they've unlocked first."""
    DO_MOB_LOOT = "doMobLoot"
    """Whether mobs should drop items and experience orbs."""
    DO_MOB_SPAWNING = "doMobSpawning"
    """Whether mobs should naturally spawn. Does not affect monster spawners."""
    DO_PATROL_SPAWNING = "doPatrolSpawning"
    """Whether patrols can spawn."""
    DO_TILE_DROPS = "doTileDrops"
    """Whether blocks should have drops."""
    DO_TRADER_SPAWNING = "doTraderSpawning"
    """Whether wandering traders can spawn."""
    DO_WEATHER_CYCLE = "doWeatherCycle"
    """Whether the weather can change naturally. The /weather command can still change weather."""
    DO_WARDEN_SPAWNING = "doWardenSpawning"
    """Whether wardens can spawn."""
    DROWNING_DAMAGE = "drowningDamage"
    """Whether the player should take damage when drowning."""
    FALL_DAMAGE = "fallDamage"
    """Whether the player should take fall damage."""
    FIRE_DAMAGE = "fireDamage"
    """Whether the player should take damage in fire, lava, campfires, or on magma blocks."""
    FORGIVE_DEAD_PLAYERS = "forgiveDeadPlayers"
    """Makes angered neutral mobs stop being angry when the targeted player dies nearby."""
    FREEZE_DAMAGE = "freezeDamage"
    """Whether the player should take damage when inside powder snow."""
    KEEP_INVENTORY = "keepInventory"
    """Whether the player should keep items and experience in their inventory after_cmds death."""
    LOG_ADMIN_COMMANDS = "logAdminCommands"
    """Whether to log admin commands to server log."""
    MAX_COMMAND_CHAIN_LENGTH = "maxCommandChainLength"
    """The maximum length of a chain of commands that can be executed during one tick. Applies to command blocks and functions."""
    MAX_ENTITY_CRAMMING = "maxEntityCramming"
    """The maximum number of pushable entities a mob or player can push, before_cmds taking 3 suffocation damage per half-second. Setting to 0 or lower disables the rule. Damage affects survival-mode or adventure-mode players, and all mobs but bats. Pushable entities include non-spectator-mode players, any mob except bats, as well as boats and minecarts."""
    MOB_GRIEFING = "mobGriefing"
    """Whether creepers, zombies, endermen, ghasts, withers, ender dragons, rabbits, sheep, villagers, silverfish, snow golems, and end crystals should be able to change blocks, and whether mobs can pick up items. When mobGriefing is disabled, piglins will not pick up gold ingots, but a player can still barter with them by using the item on the mob. Similarly, villagers will not pick up food items but can still breed until they run out of any food already in their inventory. This also affects the capability of zombie-like creatures like zombified piglins and drowned to pathfind to turtle eggs."""
    NATURAL_REGENERATION = "naturalRegeneration"
    """Whether the player can regenerate health naturally if their hunger is full enough (doesn't affect external healing, such as golden apples, the Regeneration effect, etc.)."""
    PLAYERS_SLEEPING_PERCENTAGE = "playersSleepingPercentage"
    """What percentage of players must sleep to skip the night."""
    RANDOM_TICK_SPEED = "randomTickSpeed"
    """How often a random block tick occurs (such as plant growth, leaf decay, etc.) per chunk section per game tick. 0 and negative values disables random ticks, higher numbers increase random ticks. Setting to a high integer results in high speeds of decay and growth. Numbers over 4096 make plant growth or leaf decay instantaneous."""
    REDUCED_DEBUG_INFO = "reducedDebugInfo"
    """Whether the debug screen shows all or reduced information; and whether the effects of F3 + B (entity hitboxes) and F3 + G (chunk boundaries) are shown."""
    SEND_COMMAND_FEEDBACK = "sendCommandFeedback"
    """Whether the feedback from commands executed by a player should show up in chat. Also affects the default behavior of whether command blocks store their output text."""
    SHOW_DEATH_MESSAGES = "showDeathMessages"
    """Whether death messages are put into chat when a player dies. Also affects whether a message is sent to the pet's owner when the pet dies."""
    SPAWN_RADIUS = "spawnRadius"
    """The number of blocks outward from the world spawn coordinates that a player spawns in when first joining a server or when dying without a personal spawnpoint. Has no effect on servers where the default game mode is adventure."""
    SPECTATORS_GENERATE_CHUNKS = "spectatorsGenerateChunks"
    """Whether players in spectator mode can generate chunks."""
    UNIVERSAL_ANGER = "universalAnger"
    """Makes angered neutral mobs attack any nearby player, not just the player that angered them. Works best if forgiveDeadPlayers is disabled."""

    def rule_type(rule):
      return {'announceAdvancements': 'bool', 'commandBlockOutput': 'bool', 'disableElytraMovementCheck': 'bool', 'disableRaids': 'bool', 'doDaylightCycle': 'bool', 'doEntityDrops': 'bool', 'doFireTick': 'bool', 'doInsomnia': 'bool', 'doImmediateRespawn': 'bool', 'doLimitedCrafting': 'bool', 'doMobLoot': 'bool', 'doMobSpawning': 'bool', 'doPatrolSpawning': 'bool', 'doTileDrops': 'bool', 'doTraderSpawning': 'bool', 'doWeatherCycle': 'bool', 'doWardenSpawning': 'bool', 'drowningDamage': 'bool', 'fallDamage': 'bool', 'fireDamage': 'bool', 'forgiveDeadPlayers': 'bool', 'freezeDamage': 'bool', 'keepInventory': 'bool', 'logAdminCommands': 'bool', 'maxCommandChainLength': 'int', 'maxEntityCramming': 'int', 'mobGriefing': 'bool', 'naturalRegeneration': 'bool', 'playersSleepingPercentage': 'int', 'randomTickSpeed': 'int', 'reducedDebugInfo': 'bool', 'sendCommandFeedback': 'bool', 'showDeathMessages': 'bool', 'spawnRadius': 'int', 'spectatorsGenerateChunks': 'bool', 'universalAnger': 'bool'}[rule.value]


# noinspection SpellCheckingInspection
class ScoreCriteria(ValueEnum):
    DUMMY = "dummy"
    """Score is only changed by commands, and not by game events such as death. This is useful for event flags, state mappings, currencies,..."""
    TRIGGER = "trigger"
    """Score is only changed by commands, and not by game events such as death. The /trigger command can be used by a player to set or increment/decrement their own score in an objective with this criterion. The /trigger command fails if the objective has not been "enabled" for the player using it, and the objective is disabled for the player after_cmds using the /trigger command on it. Note that the /trigger command can be used by ordinary players even if Cheats are off and they are not an Operator. This is useful for player input via /tellraw interfaces."""
    DEATH_COUNT = "deathCount"
    """Score increments automatically for a player when they die."""
    PLAYER_KILL_COUNT = "playerKillCount"
    """Score increments automatically for a player when they kill another player."""
    TOTAL_KILL_COUNT = "totalKillCount"
    """Score increments automatically for a player when they kill another player or a mob."""
    HEALTH = "health"
    """Ranges from 0 to 20 on a normal player; represents the amount of half-hearts the player has. May appear as 0 for players before_cmds their health has changed for the first time. Extra hearts and absorption hearts also count to the health score, meaning that with Attributes/Modifiers or the Health Boost or Absorption status effects, health can far surpass 20."""
    XP = "xp"
    """Matches the total amount of experience the player has collected since their last death (or in other words, their score)."""
    LEVEL = "level"
    """Matches the current experience level of the player."""
    FOOD = "food"
    """Ranges from 0 to 20; represents the amount of hunger points the player has. May appear as 0 for players before_cmds their foodLevel has changed for the first time."""
    AIR = "air"
    """Ranges from 0 to 300; represents the amount of air the player has left from swimming under water, matches the air nbt tag of the player."""
    ARMOR = "armor"
    """Ranges from 0 to 20; represents the amount of armor points the player has. May appear as 0 for players before_cmds their armor has changed for the first time."""
