import datetime
import os
from pathlib import Path


class Function:
    def __init__(self, name: Path, *commands: any):
        self.name = name
        self.commands = []
        self.add(*commands)

    def __str__(self):
        return self._warning() + '\n'.join(self.commands)

    def add(self, *commands: any):
        self.commands += (str(x) for x in commands)

    def _warning(self):
        return '# Generated by %s @ %s\n' % (os.getlogin(), datetime.datetime.now())


class Library:
    def __init__(self, path: Path, pack: str):
        self.top = path / pack / 'data' / pack / 'functions'

    def save(self, *functions: Function):
        for f in functions:
            path = self.top / f.name.with_suffix('.mcfunction')
            parent = path.parent
            parent.mkdir(parents=True, exist_ok=True)
            with open(path) as f:
                f.write(str(f))
