scoreboard players remove colored_mobs funcs 1
scoreboard players remove turtle funcs 1
scoreboard players remove rabbits funcs 1
scoreboard players remove villager_professions funcs 1
scoreboard players remove horselike funcs 1
scoreboard players remove canine funcs 1
scoreboard players remove pig funcs 1
scoreboard players remove zombie_types funcs 1
scoreboard players remove ocelot funcs 1
scoreboard players remove chicken funcs 1
scoreboard players remove panda funcs 1
scoreboard players remove sheep funcs 1
scoreboard players remove horse funcs 1
scoreboard players remove zombie_professions funcs 1
scoreboard players remove villager_levels funcs 1
scoreboard players remove turtle_eggs funcs 1
scoreboard players remove snow_golem funcs 1
scoreboard players remove llamas funcs 1
scoreboard players remove horse_armors funcs 1
scoreboard players remove villager_types funcs 1
scoreboard players remove llamas_carpets funcs 1
scoreboard players remove iron_golem funcs 1
scoreboard players remove foxes funcs 1
scoreboard players remove which_villagers funcs 1
scoreboard players remove trader_llama funcs 1
scoreboard players remove polar_bear funcs 1
scoreboard players remove switch_villagers funcs 1
scoreboard players remove bat funcs 1
scoreboard players remove cow funcs 1
scoreboard players remove parrot funcs 1
scoreboard players remove trader funcs 1
scoreboard players remove cat funcs 1
function v3:friendlies/_cur
