scoreboard players add colored_mobs funcs 1
scoreboard players add sheep funcs 1
scoreboard players add bat funcs 1
scoreboard players add pig funcs 1
scoreboard players add parrot funcs 1
scoreboard players add cow funcs 1
scoreboard players add turtle_eggs funcs 1
scoreboard players add polar_bear funcs 1
scoreboard players add horselike funcs 1
scoreboard players add llamas funcs 1
scoreboard players add horse_armors funcs 1
scoreboard players add canine funcs 1
scoreboard players add llamas_carpets funcs 1
scoreboard players add iron_golem funcs 1
scoreboard players add snow_golem funcs 1
scoreboard players add ocelot funcs 1
scoreboard players add rabbits funcs 1
scoreboard players add chicken funcs 1
scoreboard players add horse funcs 1
scoreboard players add villagers funcs 1
scoreboard players add turtle funcs 1
function v3:friendlies/_cur
