summon minecraft:horse ~1.4 ~2 ~0 {Tags:[white_horses,horse,kid,friendlies,saddle,friendlies],Variant:0,Tame:True,IsBaby:True,Age:-2147483648,CustomName:"\"White\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[270f,0f]}
summon minecraft:horse ~-1.2 ~2 ~0 {Tags:[white_horses,horse,friendlies,saddle,friendlies],Variant:0,Tame:True,CustomName:"\"White\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[270f,0f]}
summon minecraft:horse ~1.4 ~2 ~-2 {Tags:[creamy_horses,horse,kid,friendlies,saddle,friendlies],Variant:1,Tame:True,IsBaby:True,Age:-2147483648,CustomName:"\"Creamy\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[270f,0f]}
summon minecraft:horse ~-1.2 ~2 ~-2 {Tags:[creamy_horses,horse,friendlies,saddle,friendlies],Variant:1,Tame:True,CustomName:"\"Creamy\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[270f,0f]}
summon minecraft:horse ~1.4 ~2 ~-4 {Tags:[chestnut_horses,horse,kid,friendlies,saddle,friendlies],Variant:2,Tame:True,IsBaby:True,Age:-2147483648,CustomName:"\"Chestnut\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[270f,0f]}
summon minecraft:horse ~-1.2 ~2 ~-4 {Tags:[chestnut_horses,horse,friendlies,saddle,friendlies],Variant:2,Tame:True,CustomName:"\"Chestnut\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[270f,0f]}
summon minecraft:horse ~1.4 ~2 ~-6 {Tags:[brown_horses,horse,kid,friendlies,saddle,friendlies],Variant:3,Tame:True,IsBaby:True,Age:-2147483648,CustomName:"\"Brown\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[270f,0f]}
summon minecraft:horse ~-1.2 ~2 ~-6 {Tags:[brown_horses,horse,friendlies,saddle,friendlies],Variant:3,Tame:True,CustomName:"\"Brown\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[270f,0f]}
summon minecraft:horse ~1.4 ~2 ~-8 {Tags:[black_horses,horse,kid,friendlies,saddle,friendlies],Variant:4,Tame:True,IsBaby:True,Age:-2147483648,CustomName:"\"Black\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[270f,0f]}
summon minecraft:horse ~-1.2 ~2 ~-8 {Tags:[black_horses,horse,friendlies,saddle,friendlies],Variant:4,Tame:True,CustomName:"\"Black\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[270f,0f]}
summon minecraft:horse ~1.4 ~2 ~-10 {Tags:[gray_horses,horse,kid,friendlies,saddle,friendlies],Variant:5,Tame:True,IsBaby:True,Age:-2147483648,CustomName:"\"Gray\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[270f,0f]}
summon minecraft:horse ~-1.2 ~2 ~-10 {Tags:[gray_horses,horse,friendlies,saddle,friendlies],Variant:5,Tame:True,CustomName:"\"Gray\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[270f,0f]}
summon minecraft:horse ~1.4 ~2 ~-12 {Tags:[dark_brown_horses,horse,kid,friendlies,saddle,friendlies],Variant:6,Tame:True,IsBaby:True,Age:-2147483648,CustomName:"\"Dark Brown\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[270f,0f]}
summon minecraft:horse ~-1.2 ~2 ~-12 {Tags:[dark_brown_horses,horse,friendlies,saddle,friendlies],Variant:6,Tame:True,CustomName:"\"Dark Brown\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[270f,0f]}
execute at @e[tag=brown_horses,tag=kid] run setblock ~2 ~ ~ minecraft:oak_wall_sign[facing=east]{Text2:"\"Variant:\""} replace
