tp @e[tag=villager] @e[tag=death,limit=1]



scoreboard players set villagers max 2
execute unless score villagers funcs matches 0..1 run scoreboard players operation villagers funcs %= villagers max



execute if score villagers funcs matches 0 run summon minecraft:villager ~0 ~2.3 ~-2 {Tags:[villager,kid,villager,friendlies,friendlies],Profession:0,IsBaby:True,Age:-2147483648,CustomName:"\"armorer\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-2 ~2.3 ~-2 {Tags:[villager,kid,villager,friendlies,friendlies],Profession:1,IsBaby:True,Age:-2147483648,CustomName:"\"butcher\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-4 ~2.3 ~-2 {Tags:[villager,kid,villager,friendlies,friendlies],Profession:2,IsBaby:True,Age:-2147483648,CustomName:"\"cartographer\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-6 ~2.3 ~-2 {Tags:[villager,kid,villager,friendlies,friendlies],Profession:3,IsBaby:True,Age:-2147483648,CustomName:"\"cleric\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-8 ~2.3 ~-2 {Tags:[villager,kid,villager,friendlies,friendlies],Profession:4,IsBaby:True,Age:-2147483648,CustomName:"\"farmer\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-10 ~2.3 ~-2 {Tags:[villager,kid,villager,friendlies,friendlies],Profession:5,IsBaby:True,Age:-2147483648,CustomName:"\"fisherman\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-12 ~2.3 ~-2 {Tags:[villager,kid,villager,friendlies,friendlies],Profession:6,IsBaby:True,Age:-2147483648,CustomName:"\"fletcher\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-14 ~2.3 ~-2 {Tags:[villager,kid,villager,friendlies,friendlies],Profession:7,IsBaby:True,Age:-2147483648,CustomName:"\"leatherworker\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-16 ~2.3 ~-2 {Tags:[villager,kid,villager,friendlies,friendlies],Profession:8,IsBaby:True,Age:-2147483648,CustomName:"\"librarian\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-18 ~2.3 ~-2 {Tags:[villager,kid,villager,friendlies,friendlies],Profession:9,IsBaby:True,Age:-2147483648,CustomName:"\"nitwit\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-20 ~2.3 ~-2 {Tags:[villager,kid,villager,friendlies,friendlies],Profession:10,IsBaby:True,Age:-2147483648,CustomName:"\"unemployed\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-22 ~2.3 ~-2 {Tags:[villager,kid,villager,friendlies,friendlies],Profession:11,IsBaby:True,Age:-2147483648,CustomName:"\"stonemason\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-24 ~2.3 ~-2 {Tags:[villager,kid,villager,friendlies,friendlies],Profession:12,IsBaby:True,Age:-2147483648,CustomName:"\"shepherd\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-26 ~2.3 ~-2 {Tags:[villager,kid,villager,friendlies,friendlies],Profession:13,IsBaby:True,Age:-2147483648,CustomName:"\"toolsmith\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-28 ~2.3 ~-2 {Tags:[villager,kid,villager,friendlies,friendlies],Profession:14,IsBaby:True,Age:-2147483648,CustomName:"\"weaponsmith\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}


execute if score villagers funcs matches 0 run summon minecraft:villager ~0 ~2.3 ~0 {Tags:[villager,villager,friendlies,friendlies],Profession:0,CustomName:"\"armorer\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-2 ~2.3 ~0 {Tags:[villager,villager,friendlies,friendlies],Profession:1,CustomName:"\"butcher\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-4 ~2.3 ~0 {Tags:[villager,villager,friendlies,friendlies],Profession:2,CustomName:"\"cartographer\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-6 ~2.3 ~0 {Tags:[villager,villager,friendlies,friendlies],Profession:3,CustomName:"\"cleric\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-8 ~2.3 ~0 {Tags:[villager,villager,friendlies,friendlies],Profession:4,CustomName:"\"farmer\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-10 ~2.3 ~0 {Tags:[villager,villager,friendlies,friendlies],Profession:5,CustomName:"\"fisherman\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-12 ~2.3 ~0 {Tags:[villager,villager,friendlies,friendlies],Profession:6,CustomName:"\"fletcher\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-14 ~2.3 ~0 {Tags:[villager,villager,friendlies,friendlies],Profession:7,CustomName:"\"leatherworker\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-16 ~2.3 ~0 {Tags:[villager,villager,friendlies,friendlies],Profession:8,CustomName:"\"librarian\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-18 ~2.3 ~0 {Tags:[villager,villager,friendlies,friendlies],Profession:9,CustomName:"\"nitwit\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-20 ~2.3 ~0 {Tags:[villager,villager,friendlies,friendlies],Profession:10,CustomName:"\"unemployed\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-22 ~2.3 ~0 {Tags:[villager,villager,friendlies,friendlies],Profession:11,CustomName:"\"stonemason\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-24 ~2.3 ~0 {Tags:[villager,villager,friendlies,friendlies],Profession:12,CustomName:"\"shepherd\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-26 ~2.3 ~0 {Tags:[villager,villager,friendlies,friendlies],Profession:13,CustomName:"\"toolsmith\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 0 run summon minecraft:villager ~-28 ~2.3 ~0 {Tags:[villager,villager,friendlies,friendlies],Profession:14,CustomName:"\"weaponsmith\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}






execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 0 run summon minecraft:zombie_villager ~0 ~2.175 ~-2 {Tags:[zombie_villager,kid,villager,friendlies,friendlies],Profession:0,IsBaby:True,Age:-2147483648,CustomName:"\"Zombie armorer\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 0 run summon minecraft:zombie_villager ~-2 ~2.175 ~-2 {Tags:[zombie_villager,kid,villager,friendlies,friendlies],Profession:1,IsBaby:True,Age:-2147483648,CustomName:"\"Zombie butcher\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 0 run summon minecraft:zombie_villager ~-4 ~2.175 ~-2 {Tags:[zombie_villager,kid,villager,friendlies,friendlies],Profession:2,IsBaby:True,Age:-2147483648,CustomName:"\"Zombie cartographer\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 0 run summon minecraft:zombie_villager ~-6 ~2.175 ~-2 {Tags:[zombie_villager,kid,villager,friendlies,friendlies],Profession:3,IsBaby:True,Age:-2147483648,CustomName:"\"Zombie cleric\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 0 run summon minecraft:zombie_villager ~-8 ~2.175 ~-2 {Tags:[zombie_villager,kid,villager,friendlies,friendlies],Profession:4,IsBaby:True,Age:-2147483648,CustomName:"\"Zombie farmer\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 0 run summon minecraft:zombie_villager ~-10 ~2.175 ~-2 {Tags:[zombie_villager,kid,villager,friendlies,friendlies],Profession:5,IsBaby:True,Age:-2147483648,CustomName:"\"Zombie fisherman\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 0 run summon minecraft:zombie_villager ~-12 ~2.175 ~-2 {Tags:[zombie_villager,kid,villager,friendlies,friendlies],Profession:6,IsBaby:True,Age:-2147483648,CustomName:"\"Zombie fletcher\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 0 run summon minecraft:zombie_villager ~-14 ~2.175 ~-2 {Tags:[zombie_villager,kid,villager,friendlies,friendlies],Profession:7,IsBaby:True,Age:-2147483648,CustomName:"\"Zombie leatherworker\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 0 run summon minecraft:zombie_villager ~-16 ~2.175 ~-2 {Tags:[zombie_villager,kid,villager,friendlies,friendlies],Profession:8,IsBaby:True,Age:-2147483648,CustomName:"\"Zombie librarian\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 0 run summon minecraft:zombie_villager ~-18 ~2.175 ~-2 {Tags:[zombie_villager,kid,villager,friendlies,friendlies],Profession:9,IsBaby:True,Age:-2147483648,CustomName:"\"Zombie nitwit\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 0 run summon minecraft:zombie_villager ~-20 ~2.175 ~-2 {Tags:[zombie_villager,kid,villager,friendlies,friendlies],Profession:10,IsBaby:True,Age:-2147483648,CustomName:"\"Zombie unemployed\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 0 run summon minecraft:zombie_villager ~-22 ~2.175 ~-2 {Tags:[zombie_villager,kid,villager,friendlies,friendlies],Profession:11,IsBaby:True,Age:-2147483648,CustomName:"\"Zombie stonemason\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 0 run summon minecraft:zombie_villager ~-24 ~2.175 ~-2 {Tags:[zombie_villager,kid,villager,friendlies,friendlies],Profession:12,IsBaby:True,Age:-2147483648,CustomName:"\"Zombie shepherd\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 0 run summon minecraft:zombie_villager ~-26 ~2.175 ~-2 {Tags:[zombie_villager,kid,villager,friendlies,friendlies],Profession:13,IsBaby:True,Age:-2147483648,CustomName:"\"Zombie toolsmith\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 0 run summon minecraft:zombie_villager ~-28 ~2.175 ~-2 {Tags:[zombie_villager,kid,villager,friendlies,friendlies],Profession:14,IsBaby:True,Age:-2147483648,CustomName:"\"Zombie weaponsmith\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}



execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 1 run summon minecraft:chicken ~0 ~2.175 ~-2 {Tags:[chicken,villager,friendlies,friendlies],Passengers:[{id:"minecraft:zombie_villager",Profession:0,IsBaby:True,Age:-2147483648,Tags:[zombie_villager,kids],Rotation:[180f,0f],Facing:north,PersistenceRequired:True,NoAI:True,Silent:True}],CustomName:"\"Chicken\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}

execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 1 run summon minecraft:chicken ~-2 ~2.175 ~-2 {Tags:[chicken,villager,friendlies,friendlies],Passengers:[{id:"minecraft:zombie_villager",Profession:1,IsBaby:True,Age:-2147483648,Tags:[zombie_villager,kids],Rotation:[180f,0f],Facing:north,PersistenceRequired:True,NoAI:True,Silent:True}],CustomName:"\"Chicken\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}

execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 1 run summon minecraft:chicken ~-4 ~2.175 ~-2 {Tags:[chicken,villager,friendlies,friendlies],Passengers:[{id:"minecraft:zombie_villager",Profession:2,IsBaby:True,Age:-2147483648,Tags:[zombie_villager,kids],Rotation:[180f,0f],Facing:north,PersistenceRequired:True,NoAI:True,Silent:True}],CustomName:"\"Chicken\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}

execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 1 run summon minecraft:chicken ~-6 ~2.175 ~-2 {Tags:[chicken,villager,friendlies,friendlies],Passengers:[{id:"minecraft:zombie_villager",Profession:3,IsBaby:True,Age:-2147483648,Tags:[zombie_villager,kids],Rotation:[180f,0f],Facing:north,PersistenceRequired:True,NoAI:True,Silent:True}],CustomName:"\"Chicken\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}

execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 1 run summon minecraft:chicken ~-8 ~2.175 ~-2 {Tags:[chicken,villager,friendlies,friendlies],Passengers:[{id:"minecraft:zombie_villager",Profession:4,IsBaby:True,Age:-2147483648,Tags:[zombie_villager,kids],Rotation:[180f,0f],Facing:north,PersistenceRequired:True,NoAI:True,Silent:True}],CustomName:"\"Chicken\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}

execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 1 run summon minecraft:chicken ~-10 ~2.175 ~-2 {Tags:[chicken,villager,friendlies,friendlies],Passengers:[{id:"minecraft:zombie_villager",Profession:5,IsBaby:True,Age:-2147483648,Tags:[zombie_villager,kids],Rotation:[180f,0f],Facing:north,PersistenceRequired:True,NoAI:True,Silent:True}],CustomName:"\"Chicken\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}

execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 1 run summon minecraft:chicken ~-12 ~2.175 ~-2 {Tags:[chicken,villager,friendlies,friendlies],Passengers:[{id:"minecraft:zombie_villager",Profession:6,IsBaby:True,Age:-2147483648,Tags:[zombie_villager,kids],Rotation:[180f,0f],Facing:north,PersistenceRequired:True,NoAI:True,Silent:True}],CustomName:"\"Chicken\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}

execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 1 run summon minecraft:chicken ~-14 ~2.175 ~-2 {Tags:[chicken,villager,friendlies,friendlies],Passengers:[{id:"minecraft:zombie_villager",Profession:7,IsBaby:True,Age:-2147483648,Tags:[zombie_villager,kids],Rotation:[180f,0f],Facing:north,PersistenceRequired:True,NoAI:True,Silent:True}],CustomName:"\"Chicken\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}

execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 1 run summon minecraft:chicken ~-16 ~2.175 ~-2 {Tags:[chicken,villager,friendlies,friendlies],Passengers:[{id:"minecraft:zombie_villager",Profession:8,IsBaby:True,Age:-2147483648,Tags:[zombie_villager,kids],Rotation:[180f,0f],Facing:north,PersistenceRequired:True,NoAI:True,Silent:True}],CustomName:"\"Chicken\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}

execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 1 run summon minecraft:chicken ~-18 ~2.175 ~-2 {Tags:[chicken,villager,friendlies,friendlies],Passengers:[{id:"minecraft:zombie_villager",Profession:9,IsBaby:True,Age:-2147483648,Tags:[zombie_villager,kids],Rotation:[180f,0f],Facing:north,PersistenceRequired:True,NoAI:True,Silent:True}],CustomName:"\"Chicken\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}

execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 1 run summon minecraft:chicken ~-20 ~2.175 ~-2 {Tags:[chicken,villager,friendlies,friendlies],Passengers:[{id:"minecraft:zombie_villager",Profession:10,IsBaby:True,Age:-2147483648,Tags:[zombie_villager,kids],Rotation:[180f,0f],Facing:north,PersistenceRequired:True,NoAI:True,Silent:True}],CustomName:"\"Chicken\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}

execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 1 run summon minecraft:chicken ~-22 ~2.175 ~-2 {Tags:[chicken,villager,friendlies,friendlies],Passengers:[{id:"minecraft:zombie_villager",Profession:11,IsBaby:True,Age:-2147483648,Tags:[zombie_villager,kids],Rotation:[180f,0f],Facing:north,PersistenceRequired:True,NoAI:True,Silent:True}],CustomName:"\"Chicken\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}

execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 1 run summon minecraft:chicken ~-24 ~2.175 ~-2 {Tags:[chicken,villager,friendlies,friendlies],Passengers:[{id:"minecraft:zombie_villager",Profession:12,IsBaby:True,Age:-2147483648,Tags:[zombie_villager,kids],Rotation:[180f,0f],Facing:north,PersistenceRequired:True,NoAI:True,Silent:True}],CustomName:"\"Chicken\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}

execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 1 run summon minecraft:chicken ~-26 ~2.175 ~-2 {Tags:[chicken,villager,friendlies,friendlies],Passengers:[{id:"minecraft:zombie_villager",Profession:13,IsBaby:True,Age:-2147483648,Tags:[zombie_villager,kids],Rotation:[180f,0f],Facing:north,PersistenceRequired:True,NoAI:True,Silent:True}],CustomName:"\"Chicken\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}

execute if score villagers funcs matches 1 run execute if score villager_jockeys funcs matches 1 run summon minecraft:chicken ~-28 ~2.175 ~-2 {Tags:[chicken,villager,friendlies,friendlies],Passengers:[{id:"minecraft:zombie_villager",Profession:14,IsBaby:True,Age:-2147483648,Tags:[zombie_villager,kids],Rotation:[180f,0f],Facing:north,PersistenceRequired:True,NoAI:True,Silent:True}],CustomName:"\"Chicken\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}




execute if score villagers funcs matches 1 run summon minecraft:zombie_villager ~0 ~2.175 ~0 {Tags:[zombie_villager,villager,friendlies,friendlies],Profession:0,CustomName:"\"Zombie armorer\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run summon minecraft:zombie_villager ~-2 ~2.175 ~0 {Tags:[zombie_villager,villager,friendlies,friendlies],Profession:1,CustomName:"\"Zombie butcher\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run summon minecraft:zombie_villager ~-4 ~2.175 ~0 {Tags:[zombie_villager,villager,friendlies,friendlies],Profession:2,CustomName:"\"Zombie cartographer\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run summon minecraft:zombie_villager ~-6 ~2.175 ~0 {Tags:[zombie_villager,villager,friendlies,friendlies],Profession:3,CustomName:"\"Zombie cleric\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run summon minecraft:zombie_villager ~-8 ~2.175 ~0 {Tags:[zombie_villager,villager,friendlies,friendlies],Profession:4,CustomName:"\"Zombie farmer\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run summon minecraft:zombie_villager ~-10 ~2.175 ~0 {Tags:[zombie_villager,villager,friendlies,friendlies],Profession:5,CustomName:"\"Zombie fisherman\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run summon minecraft:zombie_villager ~-12 ~2.175 ~0 {Tags:[zombie_villager,villager,friendlies,friendlies],Profession:6,CustomName:"\"Zombie fletcher\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run summon minecraft:zombie_villager ~-14 ~2.175 ~0 {Tags:[zombie_villager,villager,friendlies,friendlies],Profession:7,CustomName:"\"Zombie leatherworker\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run summon minecraft:zombie_villager ~-16 ~2.175 ~0 {Tags:[zombie_villager,villager,friendlies,friendlies],Profession:8,CustomName:"\"Zombie librarian\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run summon minecraft:zombie_villager ~-18 ~2.175 ~0 {Tags:[zombie_villager,villager,friendlies,friendlies],Profession:9,CustomName:"\"Zombie nitwit\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run summon minecraft:zombie_villager ~-20 ~2.175 ~0 {Tags:[zombie_villager,villager,friendlies,friendlies],Profession:10,CustomName:"\"Zombie unemployed\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run summon minecraft:zombie_villager ~-22 ~2.175 ~0 {Tags:[zombie_villager,villager,friendlies,friendlies],Profession:11,CustomName:"\"Zombie stonemason\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run summon minecraft:zombie_villager ~-24 ~2.175 ~0 {Tags:[zombie_villager,villager,friendlies,friendlies],Profession:12,CustomName:"\"Zombie shepherd\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run summon minecraft:zombie_villager ~-26 ~2.175 ~0 {Tags:[zombie_villager,villager,friendlies,friendlies],Profession:13,CustomName:"\"Zombie toolsmith\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
execute if score villagers funcs matches 1 run summon minecraft:zombie_villager ~-28 ~2.175 ~0 {Tags:[zombie_villager,villager,friendlies,friendlies],Profession:14,CustomName:"\"Zombie weaponsmith\"",PersistenceRequired:True,NoAI:True,Silent:True,Rotation:[180f,0f]}
