kill @e[tag=signer]
summon minecraft:armor_stand ~0.000000 ~2.500000 ~0.000000 {Tags:[signer],Rotation:[270f,0f],ArmorItems:[{},{},{},{id:turtle_helmet,Count:1}]}
execute at @e[tag=signer] run fill ^0 ^0 ^0 ^-6 ^4 ^0 air
execute at @e[tag=signer] run setblock ^-3 ^4 ^0 wall_sign[facing=west]{Text2:"\"Acquatic\""}
execute at @e[tag=signer] run setblock ^-1 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Cod\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:cod ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-2 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Dolphin\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:dolphin ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-3 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Elder Guardian\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:elder_guardian ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-4 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Guardian\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:guardian ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-5 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Pufferfish\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:pufferfish ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-1 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Salmon\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:salmon ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-2 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Squid\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:squid ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-3 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Tropical Fish\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:tropical_fish ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
