kill @e[tag=signer]
summon minecraft:armor_stand ~0.000000 ~2.500000 ~0.000000 {Tags:[signer],Rotation:[270f,0f],ArmorItems:[{},{},{},{id:turtle_helmet,Count:1}]}
execute at @e[tag=signer] run fill ^0 ^0 ^0 ^-6 ^4 ^0 air
execute at @e[tag=signer] run setblock ^-3 ^4 ^0 wall_sign[facing=west]{Text2:"\"Domestic\""}
execute at @e[tag=signer] run setblock ^-1 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Cat\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:ocelot ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-2 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Chicken\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:chicken ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-3 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Cow\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:cow ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-4 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Dog\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:wolf ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-5 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Donkey\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:donkey ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-1 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Horse\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:horse ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-2 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Llama\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:llama ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-3 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Mooshroom\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:mooshroom ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-4 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Mule\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:mule ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-5 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Parrot\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:parrot ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-1 ^1 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Pig\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:pig ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-2 ^1 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Rabbit\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:rabbit ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-3 ^1 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Sheep\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:sheep ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
