kill @e[tag=signer]
summon minecraft:armor_stand ~0.000000 ~2.500000 ~0.000000 {Tags:[signer],Rotation:[270f,0f],ArmorItems:[{},{},{},{id:turtle_helmet,Count:1}]}
execute at @e[tag=signer] run fill ^0 ^0 ^0 ^-6 ^4 ^0 air
execute at @e[tag=signer] run setblock ^-3 ^4 ^0 wall_sign[facing=west]{Text2:"\"Hostile\""}
execute at @e[tag=signer] run setblock ^-1 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Cave Spider\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:cave_spider ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-2 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Chicken Jockey\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:chicken_jockey ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-3 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Creeper\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:creeper ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-4 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Drowned\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:drowned ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-5 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Endermite\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:endermite ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-1 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Evoker\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:evoker ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-2 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Husk\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:husk ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-3 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Phantom\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:phantom ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-4 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Silverfish\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:silverfish ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-5 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Skeleton Horseman\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:skeleton_horseman ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-1 ^1 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Skeleton\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:skeleton ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-2 ^1 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Spider Jockey\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:spider_jockey ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-3 ^1 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Spider\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:spider ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-4 ^1 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Stray\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:stray ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-5 ^1 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Vindicator\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:vindicator ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-1 ^0 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Witch\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:witch ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-2 ^0 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Zombie Villager\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:zombie_villager ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-3 ^0 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Zombie\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:zombie ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
