kill @e[tag=signer]
summon minecraft:armor_stand ~0.000000 ~2.500000 ~0.000000 {Tags:[signer],Rotation:[270f,0f],ArmorItems:[{},{},{},{id:turtle_helmet,Count:1}]}
execute at @e[tag=signer] run fill ^0 ^0 ^0 ^-6 ^4 ^0 air
execute at @e[tag=signer] run setblock ^-3 ^4 ^0 wall_sign[facing=west]{Text2:"\"Nether & End\""}
execute at @e[tag=signer] run setblock ^-1 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Blaze\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:blaze ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-2 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Ghast\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:ghast ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-3 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Magma Cube\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:magma_cube ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-4 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Shulker\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:shulker ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-5 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Wither Skeleton\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:wither_skeleton ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-1 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Zombie Pigman\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:zombie_pigman ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
