kill @e[tag=signer]
summon minecraft:armor_stand ~0.000000 ~2.500000 ~0.000000 {Tags:[signer],Rotation:[270f,0f],ArmorItems:[{},{},{},{id:turtle_helmet,Count:1}]}
execute at @e[tag=signer] run fill ^0 ^0 ^0 ^-6 ^4 ^0 air
execute at @e[tag=signer] run setblock ^-3 ^4 ^0 wall_sign[facing=west]{Text2:"\"Neutral\""}
execute at @e[tag=signer] run setblock ^-1 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Bat\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:bat ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-2 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Enderman\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:enderman ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-3 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Iron Golem\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:iron_golem ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-4 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Ocelot\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:ocelot ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-5 ^3 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Polar Bear\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:polar_bear ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-1 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Skeleton Horse\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:skeleton_horse ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-2 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Snow Golem\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:snow_golem ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-3 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Turtle\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:turtle ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-4 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Villager\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:villager ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
execute at @e[tag=signer] run setblock ^-5 ^2 ^0 wall_sign[facing=west]{Text2:"{\"text\":\"Wolf\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_home] positioned ~ ~2 ~ run summon minecraft:wolf ~ ~ ~\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}"} replace
