scoreboard players remove heart funcs 1
scoreboard players remove end_rod funcs 1
scoreboard players remove nautilus funcs 1
scoreboard players remove falling_dust funcs 1
scoreboard players remove splash funcs 1
scoreboard players remove dolphin funcs 1
scoreboard players remove happy_villager funcs 1
scoreboard players remove fishing funcs 1
scoreboard players remove dripping_lava funcs 1
scoreboard players remove crit funcs 1
scoreboard players remove underwater funcs 1
scoreboard players remove ambient funcs 1
scoreboard players remove damage_indicator funcs 1
scoreboard players remove angry_villager funcs 1
scoreboard players remove lava funcs 1
scoreboard players remove note funcs 1
scoreboard players remove enchanted_hit funcs 1
scoreboard players remove squid_ink funcs 1
scoreboard players remove dragon_breath funcs 1
scoreboard players remove large_smoke funcs 1
scoreboard players remove entity_effect funcs 1
scoreboard players remove campfire_smoke funcs 1
scoreboard players remove item_slime funcs 1
scoreboard players remove spit funcs 1
scoreboard players remove mycelium funcs 1
scoreboard players remove fireworks funcs 1
scoreboard players remove effect funcs 1
scoreboard players remove portal funcs 1
scoreboard players remove dust funcs 1
scoreboard players remove bubbles funcs 1
scoreboard players remove sneeze funcs 1
scoreboard players remove dripping_water funcs 1
scoreboard players remove item_snowball funcs 1
scoreboard players remove flame funcs 1
scoreboard players remove smoke funcs 1
scoreboard players remove witch funcs 1
scoreboard players remove instant_effect funcs 1
scoreboard players remove enchant funcs 1
function v3:particles/_cur
