scoreboard players add heart funcs 1
scoreboard players add end_rod funcs 1
scoreboard players add nautilus funcs 1
scoreboard players add falling_dust funcs 1
scoreboard players add splash funcs 1
scoreboard players add dolphin funcs 1
scoreboard players add happy_villager funcs 1
scoreboard players add fishing funcs 1
scoreboard players add dripping_lava funcs 1
scoreboard players add crit funcs 1
scoreboard players add underwater funcs 1
scoreboard players add ambient funcs 1
scoreboard players add damage_indicator funcs 1
scoreboard players add angry_villager funcs 1
scoreboard players add lava funcs 1
scoreboard players add note funcs 1
scoreboard players add enchanted_hit funcs 1
scoreboard players add squid_ink funcs 1
scoreboard players add dragon_breath funcs 1
scoreboard players add large_smoke funcs 1
scoreboard players add entity_effect funcs 1
scoreboard players add campfire_smoke funcs 1
scoreboard players add item_slime funcs 1
scoreboard players add spit funcs 1
scoreboard players add mycelium funcs 1
scoreboard players add fireworks funcs 1
scoreboard players add effect funcs 1
scoreboard players add portal funcs 1
scoreboard players add dust funcs 1
scoreboard players add bubbles funcs 1
scoreboard players add sneeze funcs 1
scoreboard players add dripping_water funcs 1
scoreboard players add item_snowball funcs 1
scoreboard players add flame funcs 1
scoreboard players add smoke funcs 1
scoreboard players add witch funcs 1
scoreboard players add instant_effect funcs 1
scoreboard players add enchant funcs 1
function v3:particles/_cur
