scoreboard players add ambient funcs 0
scoreboard players add angry_villager funcs 0
scoreboard players add bee_pollen funcs 0
scoreboard players add bubbles funcs 0
scoreboard players add campfire_smoke funcs 0
scoreboard players add crit funcs 0
scoreboard players add damage_indicator funcs 0
scoreboard players add dolphin funcs 0
scoreboard players add dragon_breath funcs 0
scoreboard players add dripping_honey funcs 0
scoreboard players add dripping_lava funcs 0
scoreboard players add dripping_water funcs 0
scoreboard players add dust funcs 0
scoreboard players add effect funcs 0
scoreboard players add enchant funcs 0
scoreboard players add enchanted_hit funcs 0
scoreboard players add end_rod funcs 0
scoreboard players add entity_effect funcs 0
scoreboard players add falling_dust funcs 0
scoreboard players add fireworks funcs 0
scoreboard players add fishing funcs 0
scoreboard players add flame funcs 0
scoreboard players add happy_villager funcs 0
scoreboard players add heart funcs 0
scoreboard players add instant_effect funcs 0
scoreboard players add item_slime funcs 0
scoreboard players add item_snowball funcs 0
scoreboard players add large_smoke funcs 0
scoreboard players add lava funcs 0
scoreboard players add mycelium funcs 0
scoreboard players add nautilus funcs 0
scoreboard players add note funcs 0
scoreboard players add portal funcs 0
scoreboard players add smoke funcs 0
scoreboard players add sneeze funcs 0
scoreboard players add spit funcs 0
scoreboard players add splash funcs 0
scoreboard players add squid_ink funcs 0
scoreboard players add underwater funcs 0
scoreboard players add witch funcs 0

tp @e[tag=particles] @e[tag=death,limit=1]


execute at @e[tag=ambient_home] run function v3:particles/ambient_init
execute at @e[tag=angry_villager_home] run function v3:particles/angry_villager_init
execute at @e[tag=bee_pollen_home] run function v3:particles/bee_pollen_init
execute at @e[tag=bubbles_home] run function v3:particles/bubbles_init
execute at @e[tag=campfire_smoke_home] run function v3:particles/campfire_smoke_init
execute at @e[tag=crit_home] run function v3:particles/crit_init
execute at @e[tag=damage_indicator_home] run function v3:particles/damage_indicator_init
execute at @e[tag=dolphin_home] run function v3:particles/dolphin_init
execute at @e[tag=dragon_breath_home] run function v3:particles/dragon_breath_init
execute at @e[tag=dripping_honey_home] run function v3:particles/dripping_honey_init
execute at @e[tag=dripping_lava_home] run function v3:particles/dripping_lava_init
execute at @e[tag=dripping_water_home] run function v3:particles/dripping_water_init
execute at @e[tag=dust_home] run function v3:particles/dust_init
execute at @e[tag=effect_home] run function v3:particles/effect_init
execute at @e[tag=enchant_home] run function v3:particles/enchant_init
execute at @e[tag=enchanted_hit_home] run function v3:particles/enchanted_hit_init
execute at @e[tag=end_rod_home] run function v3:particles/end_rod_init
execute at @e[tag=entity_effect_home] run function v3:particles/entity_effect_init
execute at @e[tag=falling_dust_home] run function v3:particles/falling_dust_init
execute at @e[tag=fireworks_home] run function v3:particles/fireworks_init
execute at @e[tag=fishing_home] run function v3:particles/fishing_init
execute at @e[tag=flame_home] run function v3:particles/flame_init
execute at @e[tag=happy_villager_home] run function v3:particles/happy_villager_init
execute at @e[tag=heart_home] run function v3:particles/heart_init
execute at @e[tag=instant_effect_home] run function v3:particles/instant_effect_init
execute at @e[tag=item_slime_home] run function v3:particles/item_slime_init
execute at @e[tag=item_snowball_home] run function v3:particles/item_snowball_init
execute at @e[tag=large_smoke_home] run function v3:particles/large_smoke_init
execute at @e[tag=lava_home] run function v3:particles/lava_init
execute at @e[tag=mycelium_home] run function v3:particles/mycelium_init
execute at @e[tag=nautilus_home] run function v3:particles/nautilus_init
execute at @e[tag=note_home] run function v3:particles/note_init
execute at @e[tag=portal_home] run function v3:particles/portal_init
execute at @e[tag=smoke_home] run function v3:particles/smoke_init
execute at @e[tag=sneeze_home] run function v3:particles/sneeze_init
execute at @e[tag=spit_home] run function v3:particles/spit_init
execute at @e[tag=splash_home] run function v3:particles/splash_init
execute at @e[tag=squid_ink_home] run function v3:particles/squid_ink_init
execute at @e[tag=underwater_home] run function v3:particles/underwater_init
execute at @e[tag=witch_home] run function v3:particles/witch_init
