scoreboard players add infested funcs 1
scoreboard players add job_sites funcs 1
scoreboard players add bell funcs 1
scoreboard players add brewing_stand funcs 1
scoreboard players add blocks_sign funcs 1
scoreboard players add command_blocks funcs 1
scoreboard players add job_sites_1 funcs 1
scoreboard players add cobble funcs 1
scoreboard players add cauldron funcs 1
scoreboard players add sponge funcs 1
scoreboard players add wood_blocks funcs 1
scoreboard players add job_sites_2 funcs 1
scoreboard players add skulls funcs 1
scoreboard players add end funcs 1
scoreboard players add scaffolding funcs 1
scoreboard players add anvil funcs 1
scoreboard players add grindstone funcs 1
scoreboard players add sandstone funcs 1
scoreboard players add snow funcs 1
scoreboard players add ice funcs 1
scoreboard players add bricks funcs 1
scoreboard players add campfire funcs 1
scoreboard players add music funcs 1
scoreboard players add soil funcs 1
scoreboard players add purpur funcs 1
scoreboard players add colorings funcs 1
scoreboard players add glazed_2 funcs 1
scoreboard players add stepable funcs 1
scoreboard players add slabs funcs 1
scoreboard players add glazed_1 funcs 1
scoreboard players add quartz funcs 1
scoreboard players add dirt funcs 1
scoreboard players add frosted_ice funcs 1
scoreboard players add bee_nest funcs 1
scoreboard players add composter funcs 1
scoreboard players add spawner funcs 1
scoreboard players add expand funcs 1
scoreboard players add stone funcs 1
scoreboard players add stone_bricks funcs 1
scoreboard players add structure_blocks funcs 1
scoreboard players add prismarine funcs 1
scoreboard players add ore_blocks funcs 1
scoreboard players add nether funcs 1
scoreboard players add beehive funcs 1
scoreboard players add cake funcs 1
scoreboard players add pumpkin funcs 1
scoreboard players add lantern funcs 1
function v3:blocks/_cur
