scoreboard players remove spider funcs 1
scoreboard players remove ghast funcs 1
scoreboard players remove skeleton funcs 1
scoreboard players remove endermite funcs 1
scoreboard players remove ravager funcs 1
scoreboard players remove fangs funcs 1
scoreboard players remove pigmen funcs 1
scoreboard players remove zombie_horse funcs 1
scoreboard players remove shulker funcs 1
scoreboard players remove phantom funcs 1
scoreboard players remove silverfish funcs 1
scoreboard players remove creeper funcs 1
scoreboard players remove blaze funcs 1
scoreboard players remove cave_spider funcs 1
scoreboard players remove skeleton_horse funcs 1
scoreboard players remove wither_skeleton funcs 1
scoreboard players remove enderman funcs 1
scoreboard players remove slime funcs 1
scoreboard players remove zombie funcs 1
scoreboard players remove witch funcs 1
scoreboard players remove illager funcs 1
scoreboard players remove magma_cube funcs 1
scoreboard players remove growing funcs 1
function v3:monsters/_cur
