



execute unless score 8_crops funcs matches 0.. run function 8_crops_init
scoreboard players add 8_crops funcs 1
execute unless score 8_crops funcs matches 0..9 run scoreboard players set 8_crops funcs 0
execute if score 8_crops funcs matches 0 run fill ~0 ~3 ~0 ~2 ~3 ~0 minecraft:wheat[age=0]
execute if score 8_crops funcs matches 0 run fill ~0 ~3 ~-1 ~2 ~3 ~-1 minecraft:wheat[age=1]
execute if score 8_crops funcs matches 0 run fill ~0 ~3 ~-2 ~2 ~3 ~-2 minecraft:wheat[age=2]
execute if score 8_crops funcs matches 0 run fill ~4 ~3 ~0 ~6 ~3 ~0 minecraft:carrots[age=0]
execute if score 8_crops funcs matches 0 run fill ~4 ~3 ~-1 ~6 ~3 ~-1 minecraft:carrots[age=1]
execute if score 8_crops funcs matches 0 run fill ~4 ~3 ~-2 ~6 ~3 ~-2 minecraft:carrots[age=2]
execute if score 8_crops funcs matches 0 run fill ~4 ~3 ~-4 ~6 ~3 ~-4 minecraft:potatoes[age=0]
execute if score 8_crops funcs matches 0 run fill ~4 ~3 ~-5 ~6 ~3 ~-5 minecraft:potatoes[age=1]
execute if score 8_crops funcs matches 0 run fill ~4 ~3 ~-6 ~6 ~3 ~-6 minecraft:potatoes[age=2]
execute if score 8_crops funcs matches 0 run fill ~0 ~2 ~-12 ~2 ~2 ~-12 minecraft:farmland[moisture=0]
execute if score 8_crops funcs matches 0 run fill ~0 ~2 ~-13 ~2 ~2 ~-13 minecraft:farmland[moisture=1]
execute if score 8_crops funcs matches 0 run fill ~0 ~2 ~-14 ~2 ~2 ~-14 minecraft:farmland[moisture=2]

execute if score 8_crops funcs matches 1 run fill ~0 ~3 ~0 ~2 ~3 ~0 minecraft:wheat[age=1]
execute if score 8_crops funcs matches 1 run fill ~0 ~3 ~-1 ~2 ~3 ~-1 minecraft:wheat[age=2]
execute if score 8_crops funcs matches 1 run fill ~0 ~3 ~-2 ~2 ~3 ~-2 minecraft:wheat[age=3]
execute if score 8_crops funcs matches 1 run fill ~4 ~3 ~0 ~6 ~3 ~0 minecraft:carrots[age=1]
execute if score 8_crops funcs matches 1 run fill ~4 ~3 ~-1 ~6 ~3 ~-1 minecraft:carrots[age=2]
execute if score 8_crops funcs matches 1 run fill ~4 ~3 ~-2 ~6 ~3 ~-2 minecraft:carrots[age=3]
execute if score 8_crops funcs matches 1 run fill ~4 ~3 ~-4 ~6 ~3 ~-4 minecraft:potatoes[age=1]
execute if score 8_crops funcs matches 1 run fill ~4 ~3 ~-5 ~6 ~3 ~-5 minecraft:potatoes[age=2]
execute if score 8_crops funcs matches 1 run fill ~4 ~3 ~-6 ~6 ~3 ~-6 minecraft:potatoes[age=3]
execute if score 8_crops funcs matches 1 run fill ~0 ~2 ~-12 ~2 ~2 ~-12 minecraft:farmland[moisture=1]
execute if score 8_crops funcs matches 1 run fill ~0 ~2 ~-13 ~2 ~2 ~-13 minecraft:farmland[moisture=2]
execute if score 8_crops funcs matches 1 run fill ~0 ~2 ~-14 ~2 ~2 ~-14 minecraft:farmland[moisture=3]

execute if score 8_crops funcs matches 2 run fill ~0 ~3 ~0 ~2 ~3 ~0 minecraft:wheat[age=2]
execute if score 8_crops funcs matches 2 run fill ~0 ~3 ~-1 ~2 ~3 ~-1 minecraft:wheat[age=3]
execute if score 8_crops funcs matches 2 run fill ~0 ~3 ~-2 ~2 ~3 ~-2 minecraft:wheat[age=4]
execute if score 8_crops funcs matches 2 run fill ~4 ~3 ~0 ~6 ~3 ~0 minecraft:carrots[age=2]
execute if score 8_crops funcs matches 2 run fill ~4 ~3 ~-1 ~6 ~3 ~-1 minecraft:carrots[age=3]
execute if score 8_crops funcs matches 2 run fill ~4 ~3 ~-2 ~6 ~3 ~-2 minecraft:carrots[age=4]
execute if score 8_crops funcs matches 2 run fill ~4 ~3 ~-4 ~6 ~3 ~-4 minecraft:potatoes[age=2]
execute if score 8_crops funcs matches 2 run fill ~4 ~3 ~-5 ~6 ~3 ~-5 minecraft:potatoes[age=3]
execute if score 8_crops funcs matches 2 run fill ~4 ~3 ~-6 ~6 ~3 ~-6 minecraft:potatoes[age=4]
execute if score 8_crops funcs matches 2 run fill ~0 ~2 ~-12 ~2 ~2 ~-12 minecraft:farmland[moisture=2]
execute if score 8_crops funcs matches 2 run fill ~0 ~2 ~-13 ~2 ~2 ~-13 minecraft:farmland[moisture=3]
execute if score 8_crops funcs matches 2 run fill ~0 ~2 ~-14 ~2 ~2 ~-14 minecraft:farmland[moisture=4]

execute if score 8_crops funcs matches 3 run fill ~0 ~3 ~0 ~2 ~3 ~0 minecraft:wheat[age=3]
execute if score 8_crops funcs matches 3 run fill ~0 ~3 ~-1 ~2 ~3 ~-1 minecraft:wheat[age=4]
execute if score 8_crops funcs matches 3 run fill ~0 ~3 ~-2 ~2 ~3 ~-2 minecraft:wheat[age=5]
execute if score 8_crops funcs matches 3 run fill ~4 ~3 ~0 ~6 ~3 ~0 minecraft:carrots[age=3]
execute if score 8_crops funcs matches 3 run fill ~4 ~3 ~-1 ~6 ~3 ~-1 minecraft:carrots[age=4]
execute if score 8_crops funcs matches 3 run fill ~4 ~3 ~-2 ~6 ~3 ~-2 minecraft:carrots[age=5]
execute if score 8_crops funcs matches 3 run fill ~4 ~3 ~-4 ~6 ~3 ~-4 minecraft:potatoes[age=3]
execute if score 8_crops funcs matches 3 run fill ~4 ~3 ~-5 ~6 ~3 ~-5 minecraft:potatoes[age=4]
execute if score 8_crops funcs matches 3 run fill ~4 ~3 ~-6 ~6 ~3 ~-6 minecraft:potatoes[age=5]
execute if score 8_crops funcs matches 3 run fill ~0 ~2 ~-12 ~2 ~2 ~-12 minecraft:farmland[moisture=3]
execute if score 8_crops funcs matches 3 run fill ~0 ~2 ~-13 ~2 ~2 ~-13 minecraft:farmland[moisture=4]
execute if score 8_crops funcs matches 3 run fill ~0 ~2 ~-14 ~2 ~2 ~-14 minecraft:farmland[moisture=5]

execute if score 8_crops funcs matches 4 run fill ~0 ~3 ~0 ~2 ~3 ~0 minecraft:wheat[age=4]
execute if score 8_crops funcs matches 4 run fill ~0 ~3 ~-1 ~2 ~3 ~-1 minecraft:wheat[age=5]
execute if score 8_crops funcs matches 4 run fill ~0 ~3 ~-2 ~2 ~3 ~-2 minecraft:wheat[age=6]
execute if score 8_crops funcs matches 4 run fill ~4 ~3 ~0 ~6 ~3 ~0 minecraft:carrots[age=4]
execute if score 8_crops funcs matches 4 run fill ~4 ~3 ~-1 ~6 ~3 ~-1 minecraft:carrots[age=5]
execute if score 8_crops funcs matches 4 run fill ~4 ~3 ~-2 ~6 ~3 ~-2 minecraft:carrots[age=6]
execute if score 8_crops funcs matches 4 run fill ~4 ~3 ~-4 ~6 ~3 ~-4 minecraft:potatoes[age=4]
execute if score 8_crops funcs matches 4 run fill ~4 ~3 ~-5 ~6 ~3 ~-5 minecraft:potatoes[age=5]
execute if score 8_crops funcs matches 4 run fill ~4 ~3 ~-6 ~6 ~3 ~-6 minecraft:potatoes[age=6]
execute if score 8_crops funcs matches 4 run fill ~0 ~2 ~-12 ~2 ~2 ~-12 minecraft:farmland[moisture=4]
execute if score 8_crops funcs matches 4 run fill ~0 ~2 ~-13 ~2 ~2 ~-13 minecraft:farmland[moisture=5]
execute if score 8_crops funcs matches 4 run fill ~0 ~2 ~-14 ~2 ~2 ~-14 minecraft:farmland[moisture=6]

execute if score 8_crops funcs matches 5 run fill ~0 ~3 ~0 ~2 ~3 ~0 minecraft:wheat[age=5]
execute if score 8_crops funcs matches 5 run fill ~0 ~3 ~-1 ~2 ~3 ~-1 minecraft:wheat[age=6]
execute if score 8_crops funcs matches 5 run fill ~0 ~3 ~-2 ~2 ~3 ~-2 minecraft:wheat[age=7]
execute if score 8_crops funcs matches 5 run fill ~4 ~3 ~0 ~6 ~3 ~0 minecraft:carrots[age=5]
execute if score 8_crops funcs matches 5 run fill ~4 ~3 ~-1 ~6 ~3 ~-1 minecraft:carrots[age=6]
execute if score 8_crops funcs matches 5 run fill ~4 ~3 ~-2 ~6 ~3 ~-2 minecraft:carrots[age=7]
execute if score 8_crops funcs matches 5 run fill ~4 ~3 ~-4 ~6 ~3 ~-4 minecraft:potatoes[age=5]
execute if score 8_crops funcs matches 5 run fill ~4 ~3 ~-5 ~6 ~3 ~-5 minecraft:potatoes[age=6]
execute if score 8_crops funcs matches 5 run fill ~4 ~3 ~-6 ~6 ~3 ~-6 minecraft:potatoes[age=7]
execute if score 8_crops funcs matches 5 run fill ~0 ~2 ~-12 ~2 ~2 ~-12 minecraft:farmland[moisture=5]
execute if score 8_crops funcs matches 5 run fill ~0 ~2 ~-13 ~2 ~2 ~-13 minecraft:farmland[moisture=6]
execute if score 8_crops funcs matches 5 run fill ~0 ~2 ~-14 ~2 ~2 ~-14 minecraft:farmland[moisture=7]

execute if score 8_crops funcs matches 6 run fill ~0 ~3 ~0 ~2 ~3 ~0 minecraft:wheat[age=6]
execute if score 8_crops funcs matches 6 run fill ~0 ~3 ~-1 ~2 ~3 ~-1 minecraft:wheat[age=7]
execute if score 8_crops funcs matches 6 run fill ~0 ~3 ~-2 ~2 ~3 ~-2 minecraft:wheat[age=7]
execute if score 8_crops funcs matches 6 run fill ~4 ~3 ~0 ~6 ~3 ~0 minecraft:carrots[age=6]
execute if score 8_crops funcs matches 6 run fill ~4 ~3 ~-1 ~6 ~3 ~-1 minecraft:carrots[age=7]
execute if score 8_crops funcs matches 6 run fill ~4 ~3 ~-2 ~6 ~3 ~-2 minecraft:carrots[age=7]
execute if score 8_crops funcs matches 6 run fill ~4 ~3 ~-4 ~6 ~3 ~-4 minecraft:potatoes[age=6]
execute if score 8_crops funcs matches 6 run fill ~4 ~3 ~-5 ~6 ~3 ~-5 minecraft:potatoes[age=7]
execute if score 8_crops funcs matches 6 run fill ~4 ~3 ~-6 ~6 ~3 ~-6 minecraft:potatoes[age=7]
execute if score 8_crops funcs matches 6 run fill ~0 ~2 ~-12 ~2 ~2 ~-12 minecraft:farmland[moisture=6]
execute if score 8_crops funcs matches 6 run fill ~0 ~2 ~-13 ~2 ~2 ~-13 minecraft:farmland[moisture=7]
execute if score 8_crops funcs matches 6 run fill ~0 ~2 ~-14 ~2 ~2 ~-14 minecraft:farmland[moisture=7]

execute if score 8_crops funcs matches 7 run fill ~0 ~3 ~0 ~2 ~3 ~0 minecraft:wheat[age=7]
execute if score 8_crops funcs matches 7 run fill ~0 ~3 ~-1 ~2 ~3 ~-1 minecraft:wheat[age=7]
execute if score 8_crops funcs matches 7 run fill ~0 ~3 ~-2 ~2 ~3 ~-2 minecraft:wheat[age=7]
execute if score 8_crops funcs matches 7 run fill ~4 ~3 ~0 ~6 ~3 ~0 minecraft:carrots[age=7]
execute if score 8_crops funcs matches 7 run fill ~4 ~3 ~-1 ~6 ~3 ~-1 minecraft:carrots[age=7]
execute if score 8_crops funcs matches 7 run fill ~4 ~3 ~-2 ~6 ~3 ~-2 minecraft:carrots[age=7]
execute if score 8_crops funcs matches 7 run fill ~4 ~3 ~-4 ~6 ~3 ~-4 minecraft:potatoes[age=7]
execute if score 8_crops funcs matches 7 run fill ~4 ~3 ~-5 ~6 ~3 ~-5 minecraft:potatoes[age=7]
execute if score 8_crops funcs matches 7 run fill ~4 ~3 ~-6 ~6 ~3 ~-6 minecraft:potatoes[age=7]
execute if score 8_crops funcs matches 7 run fill ~0 ~2 ~-12 ~2 ~2 ~-12 minecraft:farmland[moisture=7]
execute if score 8_crops funcs matches 7 run fill ~0 ~2 ~-13 ~2 ~2 ~-13 minecraft:farmland[moisture=7]
execute if score 8_crops funcs matches 7 run fill ~0 ~2 ~-14 ~2 ~2 ~-14 minecraft:farmland[moisture=7]

execute if score 8_crops funcs matches 8 run fill ~0 ~3 ~0 ~2 ~3 ~0 minecraft:wheat[age=7]
execute if score 8_crops funcs matches 8 run fill ~0 ~3 ~-1 ~2 ~3 ~-1 minecraft:wheat[age=7]
execute if score 8_crops funcs matches 8 run fill ~0 ~3 ~-2 ~2 ~3 ~-2 minecraft:wheat[age=0]
execute if score 8_crops funcs matches 8 run fill ~4 ~3 ~0 ~6 ~3 ~0 minecraft:carrots[age=7]
execute if score 8_crops funcs matches 8 run fill ~4 ~3 ~-1 ~6 ~3 ~-1 minecraft:carrots[age=7]
execute if score 8_crops funcs matches 8 run fill ~4 ~3 ~-2 ~6 ~3 ~-2 minecraft:carrots[age=0]
execute if score 8_crops funcs matches 8 run fill ~4 ~3 ~-4 ~6 ~3 ~-4 minecraft:potatoes[age=7]
execute if score 8_crops funcs matches 8 run fill ~4 ~3 ~-5 ~6 ~3 ~-5 minecraft:potatoes[age=7]
execute if score 8_crops funcs matches 8 run fill ~4 ~3 ~-6 ~6 ~3 ~-6 minecraft:potatoes[age=0]
execute if score 8_crops funcs matches 8 run fill ~0 ~2 ~-12 ~2 ~2 ~-12 minecraft:farmland[moisture=7]
execute if score 8_crops funcs matches 8 run fill ~0 ~2 ~-13 ~2 ~2 ~-13 minecraft:farmland[moisture=7]
execute if score 8_crops funcs matches 8 run fill ~0 ~2 ~-14 ~2 ~2 ~-14 minecraft:farmland[moisture=0]

execute if score 8_crops funcs matches 9 run fill ~0 ~3 ~0 ~2 ~3 ~0 minecraft:wheat[age=7]
execute if score 8_crops funcs matches 9 run fill ~0 ~3 ~-1 ~2 ~3 ~-1 minecraft:wheat[age=0]
execute if score 8_crops funcs matches 9 run fill ~0 ~3 ~-2 ~2 ~3 ~-2 minecraft:wheat[age=1]
execute if score 8_crops funcs matches 9 run fill ~4 ~3 ~0 ~6 ~3 ~0 minecraft:carrots[age=7]
execute if score 8_crops funcs matches 9 run fill ~4 ~3 ~-1 ~6 ~3 ~-1 minecraft:carrots[age=0]
execute if score 8_crops funcs matches 9 run fill ~4 ~3 ~-2 ~6 ~3 ~-2 minecraft:carrots[age=1]
execute if score 8_crops funcs matches 9 run fill ~4 ~3 ~-4 ~6 ~3 ~-4 minecraft:potatoes[age=7]
execute if score 8_crops funcs matches 9 run fill ~4 ~3 ~-5 ~6 ~3 ~-5 minecraft:potatoes[age=0]
execute if score 8_crops funcs matches 9 run fill ~4 ~3 ~-6 ~6 ~3 ~-6 minecraft:potatoes[age=1]
execute if score 8_crops funcs matches 9 run fill ~0 ~2 ~-12 ~2 ~2 ~-12 minecraft:farmland[moisture=7]
execute if score 8_crops funcs matches 9 run fill ~0 ~2 ~-13 ~2 ~2 ~-13 minecraft:farmland[moisture=0]
execute if score 8_crops funcs matches 9 run fill ~0 ~2 ~-14 ~2 ~2 ~-14 minecraft:farmland[moisture=1]


