scoreboard objectives add funcs dummy
scoreboard players set 2_fish vars -1
scoreboard players set 3_fish vars -1
scoreboard players set 4_crops vars -1
scoreboard players set 6_crops vars -1
scoreboard players set 8_crops vars -1
scoreboard players set acquatic vars -1
scoreboard players set all_fish vars -1
scoreboard players set all_fish vars -1
scoreboard players set anvil vars -1
scoreboard players set armors vars -1
scoreboard players set armors vars -1
scoreboard players set beam_colors vars -1
scoreboard players set brewing vars -1
scoreboard players set cake vars -1
scoreboard players set cane vars -1
scoreboard players set cane_soil vars -1
scoreboard players set cats vars -1
scoreboard players set cauldron vars -1
scoreboard players set chest vars -1
scoreboard players set cocoa vars -1
scoreboard players set colored_mobs vars -1
scoreboard players set colorings vars -1
scoreboard players set colorings vars -1
scoreboard players set columns vars -1
scoreboard players set command_blocks vars -1
scoreboard players set conduit vars -1
scoreboard players set coral vars -1
scoreboard players set creeper vars -1
scoreboard players set daylight_sensor vars -1
scoreboard players set dragon vars -1
scoreboard players set drowned vars -1
scoreboard players set ambient vars -1
scoreboard players set ambient vars -1
scoreboard players set effect_base vars -1
scoreboard players set end_mobs vars -1
scoreboard players set end_portal vars -1
scoreboard players set fangs vars -1
scoreboard players set fences vars -1
scoreboard players set fire vars -1
scoreboard players set frosted_ice vars -1
scoreboard players set furnace vars -1
scoreboard players set growing vars -1
scoreboard players set holders vars -1
scoreboard players set holders vars -1
scoreboard players set horses vars -1
scoreboard players set horses vars -1
scoreboard players set illager vars -1
scoreboard players set lava_level vars -1
scoreboard players set lever vars -1
scoreboard players set llamas vars -1
scoreboard players set llamas vars -1
scoreboard players set minecarts vars -1
scoreboard players set minerals vars -1
scoreboard players set mobs_1 vars -1
scoreboard players set mobs_2 vars -1
scoreboard players set mobs_3 vars -1
scoreboard players set mobs_4 vars -1
scoreboard players set nether_mobs vars -1
scoreboard players set note_block vars -1
scoreboard players set note_block vars -1
scoreboard players set observer vars -1
scoreboard players set observer vars -1
scoreboard players set ores vars -1
scoreboard players set panes vars -1
scoreboard players set panes vars -1
scoreboard players set parrots vars -1
scoreboard players set piston vars -1
scoreboard players set potable vars -1
scoreboard players set pressure_plate vars -1
scoreboard players set pufferfish vars -1
scoreboard players set pumpkin vars -1
scoreboard players set rabbits vars -1
scoreboard players set redstone_block vars -1
scoreboard players set sand vars -1
scoreboard players set sea_pickles vars -1
scoreboard players set snow vars -1
scoreboard players set sponge vars -1
scoreboard players set stems vars -1
scoreboard players set steppable vars -1
scoreboard players set stone vars -1
scoreboard players set structure_blocks vars -1
scoreboard players set tools vars -1
scoreboard players set topped_blocks vars -1
scoreboard players set trapped_chest vars -1
scoreboard players set tulips vars -1
scoreboard players set turtle_eggs vars -1
scoreboard players set undead vars -1
scoreboard players set villagers vars -1
scoreboard players set weapons vars -1
scoreboard players set weapons vars -1
scoreboard players set wolves vars -1
scoreboard players set wood vars -1
scoreboard players set wood vars -1
scoreboard players set wood_power vars -1
scoreboard players set wood_power vars -1
