


execute unless score note_block funcs matches 0.. run function note_block_init
scoreboard players add note_block funcs 1
execute unless score note_block funcs matches 0..24 run scoreboard players set note_block funcs 0

execute if score note_block funcs matches 0 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=0,instrument=hat]
execute if score note_block funcs matches 0 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=0,instrument=basedrum]
execute if score note_block funcs matches 0 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=0,instrument=snare]
execute if score note_block funcs matches 0 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=0,instrument=xylophone]
execute if score note_block funcs matches 0 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=0,instrument=chime]
execute if score note_block funcs matches 0 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=0,instrument=harp]
execute if score note_block funcs matches 0 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=0,instrument=guitar]
execute if score note_block funcs matches 0 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=0,instrument=bass]
execute if score note_block funcs matches 0 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=0,instrument=flute]
execute if score note_block funcs matches 0 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=0,instrument=bell]


execute if score note_block funcs matches 1 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=1,instrument=hat]
execute if score note_block funcs matches 1 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=1,instrument=basedrum]
execute if score note_block funcs matches 1 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=1,instrument=snare]
execute if score note_block funcs matches 1 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=1,instrument=xylophone]
execute if score note_block funcs matches 1 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=1,instrument=chime]
execute if score note_block funcs matches 1 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=1,instrument=harp]
execute if score note_block funcs matches 1 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=1,instrument=guitar]
execute if score note_block funcs matches 1 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=1,instrument=bass]
execute if score note_block funcs matches 1 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=1,instrument=flute]
execute if score note_block funcs matches 1 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=1,instrument=bell]


execute if score note_block funcs matches 2 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=2,instrument=hat]
execute if score note_block funcs matches 2 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=2,instrument=basedrum]
execute if score note_block funcs matches 2 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=2,instrument=snare]
execute if score note_block funcs matches 2 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=2,instrument=xylophone]
execute if score note_block funcs matches 2 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=2,instrument=chime]
execute if score note_block funcs matches 2 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=2,instrument=harp]
execute if score note_block funcs matches 2 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=2,instrument=guitar]
execute if score note_block funcs matches 2 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=2,instrument=bass]
execute if score note_block funcs matches 2 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=2,instrument=flute]
execute if score note_block funcs matches 2 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=2,instrument=bell]


execute if score note_block funcs matches 3 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=3,instrument=hat]
execute if score note_block funcs matches 3 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=3,instrument=basedrum]
execute if score note_block funcs matches 3 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=3,instrument=snare]
execute if score note_block funcs matches 3 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=3,instrument=xylophone]
execute if score note_block funcs matches 3 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=3,instrument=chime]
execute if score note_block funcs matches 3 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=3,instrument=harp]
execute if score note_block funcs matches 3 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=3,instrument=guitar]
execute if score note_block funcs matches 3 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=3,instrument=bass]
execute if score note_block funcs matches 3 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=3,instrument=flute]
execute if score note_block funcs matches 3 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=3,instrument=bell]


execute if score note_block funcs matches 4 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=4,instrument=hat]
execute if score note_block funcs matches 4 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=4,instrument=basedrum]
execute if score note_block funcs matches 4 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=4,instrument=snare]
execute if score note_block funcs matches 4 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=4,instrument=xylophone]
execute if score note_block funcs matches 4 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=4,instrument=chime]
execute if score note_block funcs matches 4 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=4,instrument=harp]
execute if score note_block funcs matches 4 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=4,instrument=guitar]
execute if score note_block funcs matches 4 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=4,instrument=bass]
execute if score note_block funcs matches 4 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=4,instrument=flute]
execute if score note_block funcs matches 4 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=4,instrument=bell]


execute if score note_block funcs matches 5 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=5,instrument=hat]
execute if score note_block funcs matches 5 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=5,instrument=basedrum]
execute if score note_block funcs matches 5 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=5,instrument=snare]
execute if score note_block funcs matches 5 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=5,instrument=xylophone]
execute if score note_block funcs matches 5 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=5,instrument=chime]
execute if score note_block funcs matches 5 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=5,instrument=harp]
execute if score note_block funcs matches 5 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=5,instrument=guitar]
execute if score note_block funcs matches 5 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=5,instrument=bass]
execute if score note_block funcs matches 5 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=5,instrument=flute]
execute if score note_block funcs matches 5 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=5,instrument=bell]


execute if score note_block funcs matches 6 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=6,instrument=hat]
execute if score note_block funcs matches 6 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=6,instrument=basedrum]
execute if score note_block funcs matches 6 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=6,instrument=snare]
execute if score note_block funcs matches 6 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=6,instrument=xylophone]
execute if score note_block funcs matches 6 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=6,instrument=chime]
execute if score note_block funcs matches 6 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=6,instrument=harp]
execute if score note_block funcs matches 6 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=6,instrument=guitar]
execute if score note_block funcs matches 6 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=6,instrument=bass]
execute if score note_block funcs matches 6 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=6,instrument=flute]
execute if score note_block funcs matches 6 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=6,instrument=bell]


execute if score note_block funcs matches 7 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=7,instrument=hat]
execute if score note_block funcs matches 7 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=7,instrument=basedrum]
execute if score note_block funcs matches 7 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=7,instrument=snare]
execute if score note_block funcs matches 7 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=7,instrument=xylophone]
execute if score note_block funcs matches 7 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=7,instrument=chime]
execute if score note_block funcs matches 7 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=7,instrument=harp]
execute if score note_block funcs matches 7 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=7,instrument=guitar]
execute if score note_block funcs matches 7 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=7,instrument=bass]
execute if score note_block funcs matches 7 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=7,instrument=flute]
execute if score note_block funcs matches 7 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=7,instrument=bell]


execute if score note_block funcs matches 8 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=8,instrument=hat]
execute if score note_block funcs matches 8 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=8,instrument=basedrum]
execute if score note_block funcs matches 8 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=8,instrument=snare]
execute if score note_block funcs matches 8 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=8,instrument=xylophone]
execute if score note_block funcs matches 8 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=8,instrument=chime]
execute if score note_block funcs matches 8 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=8,instrument=harp]
execute if score note_block funcs matches 8 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=8,instrument=guitar]
execute if score note_block funcs matches 8 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=8,instrument=bass]
execute if score note_block funcs matches 8 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=8,instrument=flute]
execute if score note_block funcs matches 8 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=8,instrument=bell]


execute if score note_block funcs matches 9 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=9,instrument=hat]
execute if score note_block funcs matches 9 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=9,instrument=basedrum]
execute if score note_block funcs matches 9 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=9,instrument=snare]
execute if score note_block funcs matches 9 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=9,instrument=xylophone]
execute if score note_block funcs matches 9 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=9,instrument=chime]
execute if score note_block funcs matches 9 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=9,instrument=harp]
execute if score note_block funcs matches 9 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=9,instrument=guitar]
execute if score note_block funcs matches 9 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=9,instrument=bass]
execute if score note_block funcs matches 9 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=9,instrument=flute]
execute if score note_block funcs matches 9 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=9,instrument=bell]


execute if score note_block funcs matches 10 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=10,instrument=hat]
execute if score note_block funcs matches 10 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=10,instrument=basedrum]
execute if score note_block funcs matches 10 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=10,instrument=snare]
execute if score note_block funcs matches 10 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=10,instrument=xylophone]
execute if score note_block funcs matches 10 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=10,instrument=chime]
execute if score note_block funcs matches 10 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=10,instrument=harp]
execute if score note_block funcs matches 10 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=10,instrument=guitar]
execute if score note_block funcs matches 10 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=10,instrument=bass]
execute if score note_block funcs matches 10 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=10,instrument=flute]
execute if score note_block funcs matches 10 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=10,instrument=bell]


execute if score note_block funcs matches 11 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=11,instrument=hat]
execute if score note_block funcs matches 11 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=11,instrument=basedrum]
execute if score note_block funcs matches 11 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=11,instrument=snare]
execute if score note_block funcs matches 11 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=11,instrument=xylophone]
execute if score note_block funcs matches 11 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=11,instrument=chime]
execute if score note_block funcs matches 11 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=11,instrument=harp]
execute if score note_block funcs matches 11 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=11,instrument=guitar]
execute if score note_block funcs matches 11 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=11,instrument=bass]
execute if score note_block funcs matches 11 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=11,instrument=flute]
execute if score note_block funcs matches 11 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=11,instrument=bell]


execute if score note_block funcs matches 12 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=12,instrument=hat]
execute if score note_block funcs matches 12 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=12,instrument=basedrum]
execute if score note_block funcs matches 12 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=12,instrument=snare]
execute if score note_block funcs matches 12 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=12,instrument=xylophone]
execute if score note_block funcs matches 12 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=12,instrument=chime]
execute if score note_block funcs matches 12 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=12,instrument=harp]
execute if score note_block funcs matches 12 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=12,instrument=guitar]
execute if score note_block funcs matches 12 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=12,instrument=bass]
execute if score note_block funcs matches 12 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=12,instrument=flute]
execute if score note_block funcs matches 12 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=12,instrument=bell]


execute if score note_block funcs matches 13 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=13,instrument=hat]
execute if score note_block funcs matches 13 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=13,instrument=basedrum]
execute if score note_block funcs matches 13 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=13,instrument=snare]
execute if score note_block funcs matches 13 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=13,instrument=xylophone]
execute if score note_block funcs matches 13 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=13,instrument=chime]
execute if score note_block funcs matches 13 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=13,instrument=harp]
execute if score note_block funcs matches 13 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=13,instrument=guitar]
execute if score note_block funcs matches 13 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=13,instrument=bass]
execute if score note_block funcs matches 13 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=13,instrument=flute]
execute if score note_block funcs matches 13 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=13,instrument=bell]


execute if score note_block funcs matches 14 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=14,instrument=hat]
execute if score note_block funcs matches 14 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=14,instrument=basedrum]
execute if score note_block funcs matches 14 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=14,instrument=snare]
execute if score note_block funcs matches 14 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=14,instrument=xylophone]
execute if score note_block funcs matches 14 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=14,instrument=chime]
execute if score note_block funcs matches 14 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=14,instrument=harp]
execute if score note_block funcs matches 14 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=14,instrument=guitar]
execute if score note_block funcs matches 14 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=14,instrument=bass]
execute if score note_block funcs matches 14 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=14,instrument=flute]
execute if score note_block funcs matches 14 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=14,instrument=bell]


execute if score note_block funcs matches 15 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=15,instrument=hat]
execute if score note_block funcs matches 15 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=15,instrument=basedrum]
execute if score note_block funcs matches 15 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=15,instrument=snare]
execute if score note_block funcs matches 15 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=15,instrument=xylophone]
execute if score note_block funcs matches 15 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=15,instrument=chime]
execute if score note_block funcs matches 15 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=15,instrument=harp]
execute if score note_block funcs matches 15 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=15,instrument=guitar]
execute if score note_block funcs matches 15 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=15,instrument=bass]
execute if score note_block funcs matches 15 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=15,instrument=flute]
execute if score note_block funcs matches 15 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=15,instrument=bell]


execute if score note_block funcs matches 16 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=16,instrument=hat]
execute if score note_block funcs matches 16 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=16,instrument=basedrum]
execute if score note_block funcs matches 16 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=16,instrument=snare]
execute if score note_block funcs matches 16 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=16,instrument=xylophone]
execute if score note_block funcs matches 16 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=16,instrument=chime]
execute if score note_block funcs matches 16 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=16,instrument=harp]
execute if score note_block funcs matches 16 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=16,instrument=guitar]
execute if score note_block funcs matches 16 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=16,instrument=bass]
execute if score note_block funcs matches 16 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=16,instrument=flute]
execute if score note_block funcs matches 16 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=16,instrument=bell]


execute if score note_block funcs matches 17 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=17,instrument=hat]
execute if score note_block funcs matches 17 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=17,instrument=basedrum]
execute if score note_block funcs matches 17 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=17,instrument=snare]
execute if score note_block funcs matches 17 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=17,instrument=xylophone]
execute if score note_block funcs matches 17 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=17,instrument=chime]
execute if score note_block funcs matches 17 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=17,instrument=harp]
execute if score note_block funcs matches 17 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=17,instrument=guitar]
execute if score note_block funcs matches 17 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=17,instrument=bass]
execute if score note_block funcs matches 17 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=17,instrument=flute]
execute if score note_block funcs matches 17 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=17,instrument=bell]


execute if score note_block funcs matches 18 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=18,instrument=hat]
execute if score note_block funcs matches 18 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=18,instrument=basedrum]
execute if score note_block funcs matches 18 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=18,instrument=snare]
execute if score note_block funcs matches 18 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=18,instrument=xylophone]
execute if score note_block funcs matches 18 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=18,instrument=chime]
execute if score note_block funcs matches 18 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=18,instrument=harp]
execute if score note_block funcs matches 18 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=18,instrument=guitar]
execute if score note_block funcs matches 18 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=18,instrument=bass]
execute if score note_block funcs matches 18 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=18,instrument=flute]
execute if score note_block funcs matches 18 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=18,instrument=bell]


execute if score note_block funcs matches 19 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=19,instrument=hat]
execute if score note_block funcs matches 19 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=19,instrument=basedrum]
execute if score note_block funcs matches 19 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=19,instrument=snare]
execute if score note_block funcs matches 19 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=19,instrument=xylophone]
execute if score note_block funcs matches 19 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=19,instrument=chime]
execute if score note_block funcs matches 19 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=19,instrument=harp]
execute if score note_block funcs matches 19 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=19,instrument=guitar]
execute if score note_block funcs matches 19 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=19,instrument=bass]
execute if score note_block funcs matches 19 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=19,instrument=flute]
execute if score note_block funcs matches 19 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=19,instrument=bell]


execute if score note_block funcs matches 20 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=20,instrument=hat]
execute if score note_block funcs matches 20 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=20,instrument=basedrum]
execute if score note_block funcs matches 20 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=20,instrument=snare]
execute if score note_block funcs matches 20 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=20,instrument=xylophone]
execute if score note_block funcs matches 20 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=20,instrument=chime]
execute if score note_block funcs matches 20 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=20,instrument=harp]
execute if score note_block funcs matches 20 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=20,instrument=guitar]
execute if score note_block funcs matches 20 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=20,instrument=bass]
execute if score note_block funcs matches 20 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=20,instrument=flute]
execute if score note_block funcs matches 20 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=20,instrument=bell]


execute if score note_block funcs matches 21 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=21,instrument=hat]
execute if score note_block funcs matches 21 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=21,instrument=basedrum]
execute if score note_block funcs matches 21 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=21,instrument=snare]
execute if score note_block funcs matches 21 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=21,instrument=xylophone]
execute if score note_block funcs matches 21 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=21,instrument=chime]
execute if score note_block funcs matches 21 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=21,instrument=harp]
execute if score note_block funcs matches 21 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=21,instrument=guitar]
execute if score note_block funcs matches 21 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=21,instrument=bass]
execute if score note_block funcs matches 21 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=21,instrument=flute]
execute if score note_block funcs matches 21 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=21,instrument=bell]


execute if score note_block funcs matches 22 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=22,instrument=hat]
execute if score note_block funcs matches 22 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=22,instrument=basedrum]
execute if score note_block funcs matches 22 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=22,instrument=snare]
execute if score note_block funcs matches 22 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=22,instrument=xylophone]
execute if score note_block funcs matches 22 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=22,instrument=chime]
execute if score note_block funcs matches 22 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=22,instrument=harp]
execute if score note_block funcs matches 22 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=22,instrument=guitar]
execute if score note_block funcs matches 22 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=22,instrument=bass]
execute if score note_block funcs matches 22 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=22,instrument=flute]
execute if score note_block funcs matches 22 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=22,instrument=bell]


execute if score note_block funcs matches 23 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=23,instrument=hat]
execute if score note_block funcs matches 23 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=23,instrument=basedrum]
execute if score note_block funcs matches 23 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=23,instrument=snare]
execute if score note_block funcs matches 23 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=23,instrument=xylophone]
execute if score note_block funcs matches 23 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=23,instrument=chime]
execute if score note_block funcs matches 23 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=23,instrument=harp]
execute if score note_block funcs matches 23 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=23,instrument=guitar]
execute if score note_block funcs matches 23 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=23,instrument=bass]
execute if score note_block funcs matches 23 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=23,instrument=flute]
execute if score note_block funcs matches 23 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=23,instrument=bell]


execute if score note_block funcs matches 24 if score instrument funcs matches 0 run setblock ~ ~3 ~ minecraft:note_block[note=24,instrument=hat]
execute if score note_block funcs matches 24 if score instrument funcs matches 1 run setblock ~ ~3 ~ minecraft:note_block[note=24,instrument=basedrum]
execute if score note_block funcs matches 24 if score instrument funcs matches 2 run setblock ~ ~3 ~ minecraft:note_block[note=24,instrument=snare]
execute if score note_block funcs matches 24 if score instrument funcs matches 3 run setblock ~ ~3 ~ minecraft:note_block[note=24,instrument=xylophone]
execute if score note_block funcs matches 24 if score instrument funcs matches 4 run setblock ~ ~3 ~ minecraft:note_block[note=24,instrument=chime]
execute if score note_block funcs matches 24 if score instrument funcs matches 5 run setblock ~ ~3 ~ minecraft:note_block[note=24,instrument=harp]
execute if score note_block funcs matches 24 if score instrument funcs matches 6 run setblock ~ ~3 ~ minecraft:note_block[note=24,instrument=guitar]
execute if score note_block funcs matches 24 if score instrument funcs matches 7 run setblock ~ ~3 ~ minecraft:note_block[note=24,instrument=bass]
execute if score note_block funcs matches 24 if score instrument funcs matches 8 run setblock ~ ~3 ~ minecraft:note_block[note=24,instrument=flute]
execute if score note_block funcs matches 24 if score instrument funcs matches 9 run setblock ~ ~3 ~ minecraft:note_block[note=24,instrument=bell]


