execute at @e[tag=phantom_home] run function v3:monsters/phantom_cur
execute at @e[tag=skeleton_horse_home] run function v3:monsters/skeleton_horse_cur
execute at @e[tag=skeleton_home] run function v3:monsters/skeleton_cur
execute at @e[tag=silverfish_home] run function v3:monsters/silverfish_cur
execute at @e[tag=creeper_home] run function v3:monsters/creeper_cur
execute at @e[tag=slime_home] run function v3:monsters/slime_cur
execute at @e[tag=illager_home] run function v3:monsters/illager_cur
execute at @e[tag=fangs_home] run function v3:monsters/fangs_cur
execute at @e[tag=witch_home] run function v3:monsters/witch_cur
execute at @e[tag=growing_home] run function v3:monsters/growing_cur
execute at @e[tag=zombie_horse_home] run function v3:monsters/zombie_horse_cur
execute at @e[tag=zombie_home] run function v3:monsters/zombie_cur
execute at @e[tag=spider_home] run function v3:monsters/spider_cur
execute at @e[tag=cave_spider_home] run function v3:monsters/cave_spider_cur
execute at @e[tag=zombie_jockey_home] run function v3:monsters/zombie_jockey_cur
execute at @e[tag=finish_home] run setblock ~1 ~ ~ minecraft:redstone_block
