function v3:blocks/_finish
function v3:acquatic/_finish
function v3:materials/_finish
function v3:diy/_finish
function v3:plants/_finish
function v3:enders/_finish
function v3:center/_finish
function v3:biomes/_finish
function v3:redstone/_finish
function v3:particles/_finish
function v3:wither/_finish
function v3:banners/_finish
function v3:arena/_finish
function v3:friendlies/_finish
function v3:containers/_finish
function v3:global/_finish
function v3:monsters/_finish
