summon minecraft:tropical_fish ~0 ~3.2 ~0 {Tags:[acquatic,kob],Variant:917504,CustomName:"\"Red-White Kob\"",NoAI:True,Silent:True,Rotation:[90f,0f]}
summon minecraft:tropical_fish ~0 ~3.2 ~1 {Tags:[acquatic,sunstreak],Variant:134217984,CustomName:"\"White-Silver Sunstreak\"",NoAI:True,Silent:True,Rotation:[90f,0f]}
summon minecraft:tropical_fish ~0 ~3.2 ~2 {Tags:[acquatic,gray_red_snooper],Variant:235340288,CustomName:"\"Gray-Red Snooper\"",NoAI:True,Silent:True,Rotation:[90f,0f]}
summon minecraft:tropical_fish ~0 ~3.2 ~3 {Tags:[acquatic,dasher],Variant:117441280,CustomName:"\"White-Gray Dasher\"",NoAI:True,Silent:True,Rotation:[90f,0f]}
summon minecraft:tropical_fish ~0 ~3.2 ~4 {Tags:[acquatic,brinely],Variant:117441536,CustomName:"\"White-Gray Brinely\"",NoAI:True,Silent:True,Rotation:[90f,0f]}
summon minecraft:tropical_fish ~0 ~3.2 ~5 {Tags:[acquatic,spotty],Variant:67110144,CustomName:"\"White-Yellow Spotter\"",NoAI:True,Silent:True,Rotation:[90f,0f]}
summon minecraft:tropical_fish ~1 ~3.2 ~0 {Tags:[acquatic,flopper],Variant:117899265,CustomName:"\"Gray Flopper\"",NoAI:True,Silent:True,Rotation:[90f,0f]}
summon minecraft:tropical_fish ~1 ~3.2 ~1 {Tags:[acquatic,stripey],Variant:117506305,CustomName:"\"Orange-Gray Stripey\"",NoAI:True,Silent:True,Rotation:[90f,0f]}
summon minecraft:tropical_fish ~1 ~3.2 ~2 {Tags:[acquatic,white_gray_glitter],Variant:117441025,CustomName:"\"White-Gray Glitter\"",NoAI:True,Silent:True,Rotation:[90f,0f]}
summon minecraft:tropical_fish ~1 ~3.2 ~3 {Tags:[acquatic,blockfish],Variant:67764993,CustomName:"\"Plum-Yellow Blockfish\"",NoAI:True,Silent:True,Rotation:[90f,0f]}
summon minecraft:tropical_fish ~1 ~3.2 ~4 {Tags:[acquatic,red_white_betty],Variant:918529,CustomName:"\"Red-White Betty\"",NoAI:True,Silent:True,Rotation:[90f,0f]}
summon minecraft:tropical_fish ~1 ~3.2 ~5 {Tags:[acquatic,clayfish],Variant:234882305,CustomName:"\"White-Red Clayfish\"",NoAI:True,Silent:True,Rotation:[90f,0f]}
setblock ~0 ~2 ~5 oak_wall_sign[facing=west,waterlogged=true]{Text1:"\"Naturally\"",Text2:"\"Occurring\"",Text3:"\"Tropical Fish\"",Text4:"\"<--------\""} destroy
