scoreboard players add bricks funcs 1
scoreboard players add blocks_sign funcs 1
scoreboard players add command_blocks funcs 1
scoreboard players add spawner funcs 1
scoreboard players add cobble funcs 1
scoreboard players add sponge funcs 1
scoreboard players add wood_blocks funcs 1
scoreboard players add skulls funcs 1
scoreboard players add end funcs 1
scoreboard players add sandstone funcs 1
scoreboard players add snow funcs 1
scoreboard players add ice funcs 1
scoreboard players add stone_bricks funcs 1
scoreboard players add purpur funcs 1
scoreboard players add soil funcs 1
scoreboard players add music funcs 1
scoreboard players add colorings funcs 1
scoreboard players add pumpkin funcs 1
scoreboard players add quartz funcs 1
scoreboard players add dirt funcs 1
scoreboard players add frosted_ice funcs 1
scoreboard players add expand funcs 1
scoreboard players add stone funcs 1
scoreboard players add colorings_turned funcs 1
scoreboard players add structure_blocks funcs 1
scoreboard players add prismarine funcs 1
scoreboard players add nether funcs 1
scoreboard players add cake funcs 1
scoreboard players add ores funcs 1
function v3:blocks/_cur
