#!/bin/sh
cd `dirname $0`
set -e
dst_dir="/Users/kcrca/Library/Application Support/minecraft/saves/RestWorld/datapacks/restworld/data/v3"
rm -rf functions
mkdir functions
/Users/kcrca/restworld/venv/bin/python /Users/kcrca/restworld/restworld/main.py
(
    cd tags/blocks
    for script in *.sh; do
	echo $script
	$script
    done
)
test -d "$dst_dir" || mkdir -p "$dst_dir"
rm -rf "$dst_dir"/functions
test -d "$dst_dir"/tags && rm -rf "$dst_dir"/tags/*
echo + cp "functions/* tags/* $dst_dir/functions/"
tar cf - functions tags | (cd "$dst_dir" ; tar xf -)
