#!/bin/zsh
cd `dirname $0`
version=$(cat version)
world=RestWorld_${1:-$version}
dst_dir="/Users/kcrca/clarity/home/saves/$world/datapacks/restworld/data/restworld"
rm -rf functions
mkdir functions
python3 /Users/kcrca/restworld/restworld/main.py || exit 1
(
    cd tags/blocks
    for script in *.sh; do
	echo $script
	$script
    done
)
test -d "$dst_dir" || mkdir -p "$dst_dir"
rm -rf "$dst_dir"/functions
test -d "$dst_dir"/tags && rm -rf "$dst_dir"/tags/*
echo + cp "functions/* tags/* $dst_dir/functions/"
tar cf - functions tags | (cd "$dst_dir" ; tar xf -)
rm -rf $dst_dir/**/.DS_Store
