#!/bin/sh
cd `dirname $0`
set -e
dst_dir="/Users/kcrca/Library/Application Support/minecraft/saves/AllStuff/datapacks/allstuff/data/v3"
rm -rf functions
mkdir functions
/Users/kcrca/allstuff/venv/bin/python /Users/kcrca/allstuff/allstuff/main.py
test -d "$dst_dir" || mkdir -p "$dst_dir"
rm -rf "$dst_dir"/functions
test -d "$dst_dir"/tags && rm -rf "$dst_dir"/tags/*
echo + cp "functions/* tags/* $dst_dir/functions/"
tar cf - functions tags | (cd "$dst_dir" ; tar xf -)
