execute at @e[tag=mushrooms_home] run function v3:plants/mushrooms_cur
execute at @e[tag=8_crops_home] run function v3:plants/8_crops_cur
execute at @e[tag=sea_pickles_home] run function v3:plants/sea_pickles_cur
execute at @e[tag=4_crops_home] run function v3:plants/4_crops_cur
execute at @e[tag=tulips_home] run function v3:plants/tulips_cur
execute at @e[tag=6_crops_home] run function v3:plants/6_crops_cur
execute at @e[tag=coral_home] run function v3:plants/coral_cur
execute at @e[tag=stems_home] run function v3:plants/stems_cur
execute at @e[tag=cocoa_home] run function v3:plants/cocoa_cur
execute at @e[tag=sapling_home] run function v3:plants/sapling_cur
execute at @e[tag=sand_home] run function v3:plants/sand_cur
execute at @e[tag=cane_home] run function v3:plants/cane_cur
execute at @e[tag=cane_soil_home] run function v3:plants/cane_soil_cur
execute at @e[tag=pottable_home] run function v3:plants/pottable_cur
execute at @e[tag=cactus_home] run function v3:plants/cactus_cur
execute at @e[tag=finish_home] run setblock ~1 ~ ~ minecraft:redstone_block
