execute unless score trades funcs matches 0.. run function trades_init
scoreboard players add trades funcs 1
scoreboard players set trades max 4
execute unless score trades funcs matches 0..3 run scoreboard players operation trades funcs %= trades max

execute if score trades funcs matches 0 run data merge entity @e[tag=trading_villager,limit=1] {Offers:{Recipes:[{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"pink_dye",Count:3b},xp:1,uses:0},{maxUses:1000,buy:{id:"diamond",Count:24b},buyB:{id:"emerald",Count:20b},sell:{id:"diamond_sword",Count:1b},xp:1,uses:0}]}}

execute if score trades funcs matches 1 run data merge entity @e[tag=trading_villager,limit=1] {Offers:{Recipes:[{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"pink_dye",Count:3b},xp:1,uses:0},{maxUses:1000,buy:{id:"diamond",Count:24b},buyB:{id:"emerald",Count:20b},sell:{id:"diamond_sword",Count:1b},xp:1,uses:0},{maxUses:1000,buy:{id:"emerald",Count:3b},buyB:{id:"air",Count:1b},sell:{id:"bubble_coral_block",Count:1b},xp:1,uses:1001},{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"pumpkin_seeds",Count:1b},xp:1,uses:0},{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"dandelion",Count:1b},xp:1,uses:0},{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"red_tulip",Count:1b},xp:1,uses:0},{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"red_dye",Count:3b},xp:1,uses:0}]}}

execute if score trades funcs matches 2 run data merge entity @e[tag=trading_villager,limit=1] {Offers:{Recipes:[{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"pink_dye",Count:3b},xp:1,uses:0},{maxUses:1000,buy:{id:"diamond",Count:24b},buyB:{id:"emerald",Count:20b},sell:{id:"diamond_sword",Count:1b},xp:1,uses:0},{maxUses:1000,buy:{id:"emerald",Count:3b},buyB:{id:"air",Count:1b},sell:{id:"bubble_coral_block",Count:1b},xp:1,uses:1001},{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"pumpkin_seeds",Count:1b},xp:1,uses:0},{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"dandelion",Count:1b},xp:1,uses:0},{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"red_tulip",Count:1b},xp:1,uses:0},{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"red_dye",Count:3b},xp:1,uses:0},{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"gunpowder",Count:1b},xp:1,uses:0},{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"pink_dye",Count:3b},xp:1,uses:1001},{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"orange_dye",Count:3b},xp:1,uses:0},{maxUses:1000,buy:{id:"emerald",Count:5b},buyB:{id:"air",Count:1b},sell:{id:"oak_sapling",Count:1b},xp:1,uses:0},{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"orange_tulip",Count:1b},xp:1,uses:1001},{maxUses:1000,buy:{id:"emerald",Count:3b},buyB:{id:"air",Count:1b},sell:{id:"packed_ice",Count:1b},xp:1,uses:0}]}}

execute if score trades funcs matches 3 run data merge entity @e[tag=trading_villager,limit=1] {Offers:{Recipes:[{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"pink_dye",Count:3b},xp:1,uses:0},{maxUses:1000,buy:{id:"diamond",Count:24b},buyB:{id:"emerald",Count:20b},sell:{id:"diamond_sword",Count:1b},xp:1,uses:0},{maxUses:1000,buy:{id:"emerald",Count:3b},buyB:{id:"air",Count:1b},sell:{id:"bubble_coral_block",Count:1b},xp:1,uses:1001},{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"pumpkin_seeds",Count:1b},xp:1,uses:0},{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"dandelion",Count:1b},xp:1,uses:0},{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"red_tulip",Count:1b},xp:1,uses:0},{maxUses:1000,buy:{id:"emerald",Count:1b},buyB:{id:"air",Count:1b},sell:{id:"red_dye",Count:3b},xp:1,uses:0}]}}
