function v3:acquatic/_cur
function v3:materials/_cur
function v3:plants/_cur
function v3:enders/_cur
function v3:center/_cur
function v3:redstone/_cur
function v3:wither/_cur
function v3:friendlies/_cur
function v3:containers/_cur
function v3:effects/_cur
function v3:monsters/_cur
