function v3:blocks/_decr
function v3:acquatic/_decr
function v3:materials/_decr
function v3:diy/_decr
function v3:plants/_decr
function v3:enders/_decr
function v3:center/_decr
function v3:redstone/_decr
function v3:wither/_decr
function v3:friendlies/_decr
function v3:containers/_decr
function v3:effects/_decr
function v3:global/_decr
function v3:monsters/_decr
